// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2CatalogRelease
    /// </summary>
    public partial class V2CatalogRelease : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogRelease" /> class.
        /// </summary>
        /// <param name="releaseId">releaseId</param>
        /// <param name="payload">payload</param>
        /// <param name="signature">signature</param>
        /// <param name="verification">verification</param>
        [JsonConstructor]
        public V2CatalogRelease(string releaseId, V2CatalogReleasePayload payload, V2CatalogReleaseSignature signature, V2CatalogReleaseVerification verification)
        {
            ReleaseId = releaseId;
            Payload = payload;
            Signature = signature;
            Verification = verification;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ReleaseId
        /// </summary>
        [JsonPropertyName("release_id")]
        public string ReleaseId { get; set; }

        /// <summary>
        /// Gets or Sets Payload
        /// </summary>
        [JsonPropertyName("payload")]
        public V2CatalogReleasePayload Payload { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [JsonPropertyName("signature")]
        public V2CatalogReleaseSignature Signature { get; set; }

        /// <summary>
        /// Gets or Sets Verification
        /// </summary>
        [JsonPropertyName("verification")]
        public V2CatalogReleaseVerification Verification { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2CatalogRelease {\n");
            sb.Append("  ReleaseId: ").Append(ReleaseId).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("  Verification: ").Append(Verification).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.ReleaseId != null) {
                // ReleaseId (string) pattern
                Regex regexReleaseId = new Regex(@"^cs2rel_[A-Za-z0-9_-]{43}$", RegexOptions.CultureInvariant);

                if (!regexReleaseId.Match(this.ReleaseId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ReleaseId, must match a pattern of " + regexReleaseId, new [] { "ReleaseId" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2CatalogRelease" />
    /// </summary>
    public partial class V2CatalogReleaseJsonConverter : JsonConverter<V2CatalogRelease>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogReleaseJsonConverter" /> class.
        /// </summary>
        public V2CatalogReleaseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2CatalogRelease" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2CatalogRelease Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> releaseId = default;
            Option<V2CatalogReleasePayload?> payload = default;
            Option<V2CatalogReleaseSignature?> signature = default;
            Option<V2CatalogReleaseVerification?> verification = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "release_id":
                            releaseId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "payload":
                            payload = new Option<V2CatalogReleasePayload?>(JsonSerializer.Deserialize<V2CatalogReleasePayload>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "signature":
                            signature = new Option<V2CatalogReleaseSignature?>(JsonSerializer.Deserialize<V2CatalogReleaseSignature>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "verification":
                            verification = new Option<V2CatalogReleaseVerification?>(JsonSerializer.Deserialize<V2CatalogReleaseVerification>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!releaseId.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogRelease.", nameof(releaseId));

            if (!payload.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogRelease.", nameof(payload));

            if (!signature.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogRelease.", nameof(signature));

            if (!verification.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogRelease.", nameof(verification));

            if (releaseId.IsSet && releaseId.Value == null)
                throw new ArgumentNullException(nameof(releaseId), "Property is not nullable for class V2CatalogRelease.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class V2CatalogRelease.");

            if (signature.IsSet && signature.Value == null)
                throw new ArgumentNullException(nameof(signature), "Property is not nullable for class V2CatalogRelease.");

            if (verification.IsSet && verification.Value == null)
                throw new ArgumentNullException(nameof(verification), "Property is not nullable for class V2CatalogRelease.");

            return new V2CatalogRelease(releaseId.Value!, payload.Value!, signature.Value!, verification.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2CatalogRelease" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogRelease"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2CatalogRelease v2CatalogRelease, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2CatalogRelease, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2CatalogRelease" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogRelease"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2CatalogRelease v2CatalogRelease, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2CatalogRelease.ReleaseId == null)
                throw new ArgumentNullException(nameof(v2CatalogRelease.ReleaseId), "Property is required for class V2CatalogRelease.");

            if (v2CatalogRelease.Payload == null)
                throw new ArgumentNullException(nameof(v2CatalogRelease.Payload), "Property is required for class V2CatalogRelease.");

            if (v2CatalogRelease.Signature == null)
                throw new ArgumentNullException(nameof(v2CatalogRelease.Signature), "Property is required for class V2CatalogRelease.");

            if (v2CatalogRelease.Verification == null)
                throw new ArgumentNullException(nameof(v2CatalogRelease.Verification), "Property is required for class V2CatalogRelease.");

            writer.WriteString("release_id", v2CatalogRelease.ReleaseId);

            writer.WritePropertyName("payload");
            JsonSerializer.Serialize(writer, v2CatalogRelease.Payload, jsonSerializerOptions);
            writer.WritePropertyName("signature");
            JsonSerializer.Serialize(writer, v2CatalogRelease.Signature, jsonSerializerOptions);
            writer.WritePropertyName("verification");
            JsonSerializer.Serialize(writer, v2CatalogRelease.Verification, jsonSerializerOptions);
        }
    }
}
