// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2Capability
    /// </summary>
    public partial class V2Capability : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2Capability" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="state">state</param>
        /// <param name="requiredScopes">requiredScopes</param>
        /// <param name="boundary">boundary</param>
        [JsonConstructor]
        public V2Capability(string name, StateEnum state, List<string> requiredScopes, BoundaryEnum boundary)
        {
            Name = name;
            State = state;
            RequiredScopes = requiredScopes;
            Boundary = boundary;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines State
        /// </summary>
        public enum StateEnum
        {
            /// <summary>
            /// Enum Production for value: production
            /// </summary>
            Production = 1,

            /// <summary>
            /// Enum Unavailable for value: unavailable
            /// </summary>
            Unavailable = 2,

            /// <summary>
            /// Enum Planned for value: planned
            /// </summary>
            Planned = 3
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StateEnum StateEnumFromString(string value)
        {
            if (value.Equals("production"))
                return StateEnum.Production;

            if (value.Equals("unavailable"))
                return StateEnum.Unavailable;

            if (value.Equals("planned"))
                return StateEnum.Planned;

            throw new NotImplementedException($"Could not convert value to type StateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StateEnum? StateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("production"))
                return StateEnum.Production;

            if (value.Equals("unavailable"))
                return StateEnum.Unavailable;

            if (value.Equals("planned"))
                return StateEnum.Planned;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StateEnumToJsonValue(StateEnum value)
        {
            if (value == StateEnum.Production)
                return "production";

            if (value == StateEnum.Unavailable)
                return "unavailable";

            if (value == StateEnum.Planned)
                return "planned";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public StateEnum State { get; set; }

        /// <summary>
        /// Defines Boundary
        /// </summary>
        public enum BoundaryEnum
        {
            /// <summary>
            /// Enum Data for value: data
            /// </summary>
            Data = 1,

            /// <summary>
            /// Enum Media for value: media
            /// </summary>
            Media = 2,

            /// <summary>
            /// Enum Control for value: control
            /// </summary>
            Control = 3,

            /// <summary>
            /// Enum Automation for value: automation
            /// </summary>
            Automation = 4
        }

        /// <summary>
        /// Returns a <see cref="BoundaryEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static BoundaryEnum BoundaryEnumFromString(string value)
        {
            if (value.Equals("data"))
                return BoundaryEnum.Data;

            if (value.Equals("media"))
                return BoundaryEnum.Media;

            if (value.Equals("control"))
                return BoundaryEnum.Control;

            if (value.Equals("automation"))
                return BoundaryEnum.Automation;

            throw new NotImplementedException($"Could not convert value to type BoundaryEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="BoundaryEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BoundaryEnum? BoundaryEnumFromStringOrDefault(string value)
        {
            if (value.Equals("data"))
                return BoundaryEnum.Data;

            if (value.Equals("media"))
                return BoundaryEnum.Media;

            if (value.Equals("control"))
                return BoundaryEnum.Control;

            if (value.Equals("automation"))
                return BoundaryEnum.Automation;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BoundaryEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string BoundaryEnumToJsonValue(BoundaryEnum value)
        {
            if (value == BoundaryEnum.Data)
                return "data";

            if (value == BoundaryEnum.Media)
                return "media";

            if (value == BoundaryEnum.Control)
                return "control";

            if (value == BoundaryEnum.Automation)
                return "automation";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Boundary
        /// </summary>
        [JsonPropertyName("boundary")]
        public BoundaryEnum Boundary { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets RequiredScopes
        /// </summary>
        [JsonPropertyName("required_scopes")]
        public List<string> RequiredScopes { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2Capability {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  RequiredScopes: ").Append(RequiredScopes).Append("\n");
            sb.Append("  Boundary: ").Append(Boundary).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2Capability" />
    /// </summary>
    public partial class V2CapabilityJsonConverter : JsonConverter<V2Capability>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2CapabilityJsonConverter" /> class.
        /// </summary>
        public V2CapabilityJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2Capability" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2Capability Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<V2Capability.StateEnum?> state = default;
            Option<List<string>?> requiredScopes = default;
            Option<V2Capability.BoundaryEnum?> boundary = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                            {
                                V2Capability.StateEnum? stateValue = V2Capability.StateEnumFromStringOrDefault(stateRawValue);
                                if (stateValue == null)
                                    throw new JsonException();
                                state = new Option<V2Capability.StateEnum?>(stateValue);
                            }
                            break;
                        case "required_scopes":
                            requiredScopes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "boundary":
                            string? boundaryRawValue = utf8JsonReader.GetString();
                            if (boundaryRawValue != null)
                            {
                                V2Capability.BoundaryEnum? boundaryValue = V2Capability.BoundaryEnumFromStringOrDefault(boundaryRawValue);
                                if (boundaryValue == null)
                                    throw new JsonException();
                                boundary = new Option<V2Capability.BoundaryEnum?>(boundaryValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class V2Capability.", nameof(name));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class V2Capability.", nameof(state));

            if (!requiredScopes.IsSet)
                throw new ArgumentException("Property is required for class V2Capability.", nameof(requiredScopes));

            if (!boundary.IsSet)
                throw new ArgumentException("Property is required for class V2Capability.", nameof(boundary));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class V2Capability.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class V2Capability.");

            if (requiredScopes.IsSet && requiredScopes.Value == null)
                throw new ArgumentNullException(nameof(requiredScopes), "Property is not nullable for class V2Capability.");

            if (boundary.IsSet && boundary.Value == null)
                throw new ArgumentNullException(nameof(boundary), "Property is not nullable for class V2Capability.");

            return new V2Capability(name.Value!, state.Value!.Value!, requiredScopes.Value!, boundary.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2Capability" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2Capability"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2Capability v2Capability, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2Capability, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2Capability" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2Capability"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2Capability v2Capability, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2Capability.Name == null)
                throw new ArgumentNullException(nameof(v2Capability.Name), "Property is required for class V2Capability.");

            if (v2Capability.RequiredScopes == null)
                throw new ArgumentNullException(nameof(v2Capability.RequiredScopes), "Property is required for class V2Capability.");

            writer.WriteString("name", v2Capability.Name);

            var stateRawValue = V2Capability.StateEnumToJsonValue(v2Capability.State);
            writer.WriteString("state", stateRawValue);
            writer.WritePropertyName("required_scopes");
            JsonSerializer.Serialize(writer, v2Capability.RequiredScopes, jsonSerializerOptions);
            var boundaryRawValue = V2Capability.BoundaryEnumToJsonValue(v2Capability.Boundary);
            writer.WriteString("boundary", boundaryRawValue);
        }
    }
}
