// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2CatalogReleaseExportDownload
    /// </summary>
    public partial class V2CatalogReleaseExportDownload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogReleaseExportDownload" /> class.
        /// </summary>
        /// <param name="url">Temporary HTTPS download URL.</param>
        /// <param name="expiresAt">expiresAt</param>
        [JsonConstructor]
        public V2CatalogReleaseExportDownload(string url, DateTime expiresAt)
        {
            Url = url;
            ExpiresAt = expiresAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Temporary HTTPS download URL.
        /// </summary>
        /// <value>Temporary HTTPS download URL.</value>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expires_at")]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2CatalogReleaseExportDownload {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2CatalogReleaseExportDownload" />
    /// </summary>
    public partial class V2CatalogReleaseExportDownloadJsonConverter : JsonConverter<V2CatalogReleaseExportDownload>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogReleaseExportDownloadJsonConverter" /> class.
        /// </summary>
        public V2CatalogReleaseExportDownloadJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2CatalogReleaseExportDownload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2CatalogReleaseExportDownload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<DateTime?> expiresAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogReleaseExportDownload.", nameof(url));

            if (!expiresAt.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogReleaseExportDownload.", nameof(expiresAt));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class V2CatalogReleaseExportDownload.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class V2CatalogReleaseExportDownload.");

            return new V2CatalogReleaseExportDownload(url.Value!, expiresAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2CatalogReleaseExportDownload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogReleaseExportDownload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2CatalogReleaseExportDownload v2CatalogReleaseExportDownload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2CatalogReleaseExportDownload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2CatalogReleaseExportDownload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogReleaseExportDownload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2CatalogReleaseExportDownload v2CatalogReleaseExportDownload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2CatalogReleaseExportDownload.Url == null)
                throw new ArgumentNullException(nameof(v2CatalogReleaseExportDownload.Url), "Property is required for class V2CatalogReleaseExportDownload.");

            writer.WriteString("url", v2CatalogReleaseExportDownload.Url);

            writer.WriteString("expires_at", v2CatalogReleaseExportDownload.ExpiresAt.ToString(ExpiresAtFormat));
        }
    }
}
