// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2CatalogRenderPattern
    /// </summary>
    public partial class V2CatalogRenderPattern : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogRenderPattern" /> class.
        /// </summary>
        /// <param name="supported">supported</param>
        /// <param name="minimum">Exact minimum accepted pattern value. Omitted when pattern is unsupported.</param>
        /// <param name="maximum">Exact maximum accepted pattern value. Omitted when pattern is unsupported.</param>
        /// <param name="default">Renderer default inside the accepted pattern range. Omitted when pattern is unsupported.</param>
        [JsonConstructor]
        public V2CatalogRenderPattern(bool supported, Option<int?> minimum = default, Option<int?> maximum = default, Option<int?> @default = default)
        {
            Supported = supported;
            MinimumOption = minimum;
            MaximumOption = maximum;
            DefaultOption = @default;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Supported
        /// </summary>
        [JsonPropertyName("supported")]
        public bool Supported { get; set; }

        /// <summary>
        /// Used to track the state of Minimum
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MinimumOption { get; private set; }

        /// <summary>
        /// Exact minimum accepted pattern value. Omitted when pattern is unsupported.
        /// </summary>
        /// <value>Exact minimum accepted pattern value. Omitted when pattern is unsupported.</value>
        [JsonPropertyName("minimum")]
        public int? Minimum { get { return this.MinimumOption.Value; } set { this.MinimumOption = new(value); } }

        /// <summary>
        /// Used to track the state of Maximum
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MaximumOption { get; private set; }

        /// <summary>
        /// Exact maximum accepted pattern value. Omitted when pattern is unsupported.
        /// </summary>
        /// <value>Exact maximum accepted pattern value. Omitted when pattern is unsupported.</value>
        [JsonPropertyName("maximum")]
        public int? Maximum { get { return this.MaximumOption.Value; } set { this.MaximumOption = new(value); } }

        /// <summary>
        /// Used to track the state of Default
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DefaultOption { get; private set; }

        /// <summary>
        /// Renderer default inside the accepted pattern range. Omitted when pattern is unsupported.
        /// </summary>
        /// <value>Renderer default inside the accepted pattern range. Omitted when pattern is unsupported.</value>
        [JsonPropertyName("default")]
        public int? Default { get { return this.DefaultOption.Value; } set { this.DefaultOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2CatalogRenderPattern {\n");
            sb.Append("  Supported: ").Append(Supported).Append("\n");
            sb.Append("  Minimum: ").Append(Minimum).Append("\n");
            sb.Append("  Maximum: ").Append(Maximum).Append("\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Minimum (int) maximum
            if (this.MinimumOption.IsSet && this.MinimumOption.Value > (int)100000)
            {
                yield return new ValidationResult("Invalid value for Minimum, must be a value less than or equal to 100000.", new [] { "Minimum" });
            }

            // Minimum (int) minimum
            if (this.MinimumOption.IsSet && this.MinimumOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for Minimum, must be a value greater than or equal to 0.", new [] { "Minimum" });
            }

            // Maximum (int) maximum
            if (this.MaximumOption.IsSet && this.MaximumOption.Value > (int)100000)
            {
                yield return new ValidationResult("Invalid value for Maximum, must be a value less than or equal to 100000.", new [] { "Maximum" });
            }

            // Maximum (int) minimum
            if (this.MaximumOption.IsSet && this.MaximumOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for Maximum, must be a value greater than or equal to 0.", new [] { "Maximum" });
            }

            // Default (int) maximum
            if (this.DefaultOption.IsSet && this.DefaultOption.Value > (int)100000)
            {
                yield return new ValidationResult("Invalid value for Default, must be a value less than or equal to 100000.", new [] { "Default" });
            }

            // Default (int) minimum
            if (this.DefaultOption.IsSet && this.DefaultOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for Default, must be a value greater than or equal to 0.", new [] { "Default" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2CatalogRenderPattern" />
    /// </summary>
    public partial class V2CatalogRenderPatternJsonConverter : JsonConverter<V2CatalogRenderPattern>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogRenderPatternJsonConverter" /> class.
        /// </summary>
        public V2CatalogRenderPatternJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2CatalogRenderPattern" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2CatalogRenderPattern Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> supported = default;
            Option<int?> minimum = default;
            Option<int?> maximum = default;
            Option<int?> varDefault = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "supported":
                            supported = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "minimum":
                            minimum = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "maximum":
                            maximum = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "default":
                            varDefault = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!supported.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogRenderPattern.", nameof(supported));

            if (supported.IsSet && supported.Value == null)
                throw new ArgumentNullException(nameof(supported), "Property is not nullable for class V2CatalogRenderPattern.");

            if (minimum.IsSet && minimum.Value == null)
                throw new ArgumentNullException(nameof(minimum), "Property is not nullable for class V2CatalogRenderPattern.");

            if (maximum.IsSet && maximum.Value == null)
                throw new ArgumentNullException(nameof(maximum), "Property is not nullable for class V2CatalogRenderPattern.");

            if (varDefault.IsSet && varDefault.Value == null)
                throw new ArgumentNullException(nameof(varDefault), "Property is not nullable for class V2CatalogRenderPattern.");

            return new V2CatalogRenderPattern(supported.Value!.Value!, minimum, maximum, varDefault);
        }

        /// <summary>
        /// Serializes a <see cref="V2CatalogRenderPattern" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogRenderPattern"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2CatalogRenderPattern v2CatalogRenderPattern, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2CatalogRenderPattern, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2CatalogRenderPattern" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogRenderPattern"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2CatalogRenderPattern v2CatalogRenderPattern, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("supported", v2CatalogRenderPattern.Supported);

            if (v2CatalogRenderPattern.MinimumOption.IsSet)
                writer.WriteNumber("minimum", v2CatalogRenderPattern.MinimumOption.Value!.Value);

            if (v2CatalogRenderPattern.MaximumOption.IsSet)
                writer.WriteNumber("maximum", v2CatalogRenderPattern.MaximumOption.Value!.Value);

            if (v2CatalogRenderPattern.DefaultOption.IsSet)
                writer.WriteNumber("default", v2CatalogRenderPattern.DefaultOption.Value!.Value);
        }
    }
}
