// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2CatalogCounts
    /// </summary>
    public partial class V2CatalogCounts : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogCounts" /> class.
        /// </summary>
        /// <param name="items">items</param>
        /// <param name="collections">collections</param>
        /// <param name="collectionMemberships">collectionMemberships</param>
        /// <param name="containers">containers</param>
        /// <param name="containerDrops">containerDrops</param>
        [JsonConstructor]
        public V2CatalogCounts(int items, int collections, int collectionMemberships, int containers, int containerDrops)
        {
            Items = items;
            Collections = collections;
            CollectionMemberships = collectionMemberships;
            Containers = containers;
            ContainerDrops = containerDrops;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public int Items { get; set; }

        /// <summary>
        /// Gets or Sets Collections
        /// </summary>
        [JsonPropertyName("collections")]
        public int Collections { get; set; }

        /// <summary>
        /// Gets or Sets CollectionMemberships
        /// </summary>
        [JsonPropertyName("collection_memberships")]
        public int CollectionMemberships { get; set; }

        /// <summary>
        /// Gets or Sets Containers
        /// </summary>
        [JsonPropertyName("containers")]
        public int Containers { get; set; }

        /// <summary>
        /// Gets or Sets ContainerDrops
        /// </summary>
        [JsonPropertyName("container_drops")]
        public int ContainerDrops { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2CatalogCounts {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Collections: ").Append(Collections).Append("\n");
            sb.Append("  CollectionMemberships: ").Append(CollectionMemberships).Append("\n");
            sb.Append("  Containers: ").Append(Containers).Append("\n");
            sb.Append("  ContainerDrops: ").Append(ContainerDrops).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Items (int) minimum
            if (this.Items < (int)0)
            {
                yield return new ValidationResult("Invalid value for Items, must be a value greater than or equal to 0.", new [] { "Items" });
            }

            // Collections (int) minimum
            if (this.Collections < (int)0)
            {
                yield return new ValidationResult("Invalid value for Collections, must be a value greater than or equal to 0.", new [] { "Collections" });
            }

            // CollectionMemberships (int) minimum
            if (this.CollectionMemberships < (int)0)
            {
                yield return new ValidationResult("Invalid value for CollectionMemberships, must be a value greater than or equal to 0.", new [] { "CollectionMemberships" });
            }

            // Containers (int) minimum
            if (this.Containers < (int)0)
            {
                yield return new ValidationResult("Invalid value for Containers, must be a value greater than or equal to 0.", new [] { "Containers" });
            }

            // ContainerDrops (int) minimum
            if (this.ContainerDrops < (int)0)
            {
                yield return new ValidationResult("Invalid value for ContainerDrops, must be a value greater than or equal to 0.", new [] { "ContainerDrops" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2CatalogCounts" />
    /// </summary>
    public partial class V2CatalogCountsJsonConverter : JsonConverter<V2CatalogCounts>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogCountsJsonConverter" /> class.
        /// </summary>
        public V2CatalogCountsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2CatalogCounts" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2CatalogCounts Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> items = default;
            Option<int?> collections = default;
            Option<int?> collectionMemberships = default;
            Option<int?> containers = default;
            Option<int?> containerDrops = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "items":
                            items = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "collections":
                            collections = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "collection_memberships":
                            collectionMemberships = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "containers":
                            containers = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "container_drops":
                            containerDrops = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!items.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogCounts.", nameof(items));

            if (!collections.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogCounts.", nameof(collections));

            if (!collectionMemberships.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogCounts.", nameof(collectionMemberships));

            if (!containers.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogCounts.", nameof(containers));

            if (!containerDrops.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogCounts.", nameof(containerDrops));

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class V2CatalogCounts.");

            if (collections.IsSet && collections.Value == null)
                throw new ArgumentNullException(nameof(collections), "Property is not nullable for class V2CatalogCounts.");

            if (collectionMemberships.IsSet && collectionMemberships.Value == null)
                throw new ArgumentNullException(nameof(collectionMemberships), "Property is not nullable for class V2CatalogCounts.");

            if (containers.IsSet && containers.Value == null)
                throw new ArgumentNullException(nameof(containers), "Property is not nullable for class V2CatalogCounts.");

            if (containerDrops.IsSet && containerDrops.Value == null)
                throw new ArgumentNullException(nameof(containerDrops), "Property is not nullable for class V2CatalogCounts.");

            return new V2CatalogCounts(items.Value!.Value!, collections.Value!.Value!, collectionMemberships.Value!.Value!, containers.Value!.Value!, containerDrops.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2CatalogCounts" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogCounts"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2CatalogCounts v2CatalogCounts, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2CatalogCounts, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2CatalogCounts" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogCounts"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2CatalogCounts v2CatalogCounts, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("items", v2CatalogCounts.Items);

            writer.WriteNumber("collections", v2CatalogCounts.Collections);

            writer.WriteNumber("collection_memberships", v2CatalogCounts.CollectionMemberships);

            writer.WriteNumber("containers", v2CatalogCounts.Containers);

            writer.WriteNumber("container_drops", v2CatalogCounts.ContainerDrops);
        }
    }
}
