// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2CatalogReleaseSignature
    /// </summary>
    public partial class V2CatalogReleaseSignature : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogReleaseSignature" /> class.
        /// </summary>
        /// <param name="algorithm">algorithm</param>
        /// <param name="keyId">keyId</param>
        /// <param name="value">value</param>
        [JsonConstructor]
        public V2CatalogReleaseSignature(AlgorithmEnum algorithm, string keyId, string value)
        {
            Algorithm = algorithm;
            KeyId = keyId;
            Value = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Algorithm
        /// </summary>
        public enum AlgorithmEnum
        {
            /// <summary>
            /// Enum Ed25519 for value: ed25519
            /// </summary>
            Ed25519 = 1
        }

        /// <summary>
        /// Returns a <see cref="AlgorithmEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static AlgorithmEnum AlgorithmEnumFromString(string value)
        {
            if (value.Equals("ed25519"))
                return AlgorithmEnum.Ed25519;

            throw new NotImplementedException($"Could not convert value to type AlgorithmEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="AlgorithmEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AlgorithmEnum? AlgorithmEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ed25519"))
                return AlgorithmEnum.Ed25519;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AlgorithmEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string AlgorithmEnumToJsonValue(AlgorithmEnum value)
        {
            if (value == AlgorithmEnum.Ed25519)
                return "ed25519";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Algorithm
        /// </summary>
        [JsonPropertyName("algorithm")]
        public AlgorithmEnum Algorithm { get; set; }

        /// <summary>
        /// Gets or Sets KeyId
        /// </summary>
        [JsonPropertyName("key_id")]
        public string KeyId { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2CatalogReleaseSignature {\n");
            sb.Append("  Algorithm: ").Append(Algorithm).Append("\n");
            sb.Append("  KeyId: ").Append(KeyId).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2CatalogReleaseSignature" />
    /// </summary>
    public partial class V2CatalogReleaseSignatureJsonConverter : JsonConverter<V2CatalogReleaseSignature>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2CatalogReleaseSignatureJsonConverter" /> class.
        /// </summary>
        public V2CatalogReleaseSignatureJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2CatalogReleaseSignature" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2CatalogReleaseSignature Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2CatalogReleaseSignature.AlgorithmEnum?> algorithm = default;
            Option<string?> keyId = default;
            Option<string?> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "algorithm":
                            string? algorithmRawValue = utf8JsonReader.GetString();
                            if (algorithmRawValue != null)
                            {
                                V2CatalogReleaseSignature.AlgorithmEnum? algorithmValue = V2CatalogReleaseSignature.AlgorithmEnumFromStringOrDefault(algorithmRawValue);
                                if (algorithmValue == null)
                                    throw new JsonException();
                                algorithm = new Option<V2CatalogReleaseSignature.AlgorithmEnum?>(algorithmValue);
                            }
                            break;
                        case "key_id":
                            keyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!algorithm.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogReleaseSignature.", nameof(algorithm));

            if (!keyId.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogReleaseSignature.", nameof(keyId));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class V2CatalogReleaseSignature.", nameof(value));

            if (algorithm.IsSet && algorithm.Value == null)
                throw new ArgumentNullException(nameof(algorithm), "Property is not nullable for class V2CatalogReleaseSignature.");

            if (keyId.IsSet && keyId.Value == null)
                throw new ArgumentNullException(nameof(keyId), "Property is not nullable for class V2CatalogReleaseSignature.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class V2CatalogReleaseSignature.");

            return new V2CatalogReleaseSignature(algorithm.Value!.Value!, keyId.Value!, value.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2CatalogReleaseSignature" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogReleaseSignature"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2CatalogReleaseSignature v2CatalogReleaseSignature, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2CatalogReleaseSignature, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2CatalogReleaseSignature" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2CatalogReleaseSignature"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2CatalogReleaseSignature v2CatalogReleaseSignature, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2CatalogReleaseSignature.KeyId == null)
                throw new ArgumentNullException(nameof(v2CatalogReleaseSignature.KeyId), "Property is required for class V2CatalogReleaseSignature.");

            if (v2CatalogReleaseSignature.Value == null)
                throw new ArgumentNullException(nameof(v2CatalogReleaseSignature.Value), "Property is required for class V2CatalogReleaseSignature.");

            var algorithmRawValue = V2CatalogReleaseSignature.AlgorithmEnumToJsonValue(v2CatalogReleaseSignature.Algorithm);
            writer.WriteString("algorithm", algorithmRawValue);
            writer.WriteString("key_id", v2CatalogReleaseSignature.KeyId);

            writer.WriteString("value", v2CatalogReleaseSignature.Value);
        }
    }
}
