// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2EncryptedDeliveryRequest
    /// </summary>
    public partial class V2EncryptedDeliveryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2EncryptedDeliveryRequest" /> class.
        /// </summary>
        /// <param name="deliveryPublicKey">Base64 DER SubjectPublicKeyInfo for a caller-owned P-256 ECDH key</param>
        [JsonConstructor]
        public V2EncryptedDeliveryRequest(byte[] deliveryPublicKey)
        {
            DeliveryPublicKey = deliveryPublicKey;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Base64 DER SubjectPublicKeyInfo for a caller-owned P-256 ECDH key
        /// </summary>
        /// <value>Base64 DER SubjectPublicKeyInfo for a caller-owned P-256 ECDH key</value>
        [JsonPropertyName("delivery_public_key")]
        public byte[] DeliveryPublicKey { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2EncryptedDeliveryRequest {\n");
            sb.Append("  DeliveryPublicKey: ").Append(DeliveryPublicKey).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2EncryptedDeliveryRequest" />
    /// </summary>
    public partial class V2EncryptedDeliveryRequestJsonConverter : JsonConverter<V2EncryptedDeliveryRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2EncryptedDeliveryRequestJsonConverter" /> class.
        /// </summary>
        public V2EncryptedDeliveryRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2EncryptedDeliveryRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2EncryptedDeliveryRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<byte[]?> deliveryPublicKey = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "delivery_public_key":
                            deliveryPublicKey = new Option<byte[]?>(JsonSerializer.Deserialize<byte[]>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!deliveryPublicKey.IsSet)
                throw new ArgumentException("Property is required for class V2EncryptedDeliveryRequest.", nameof(deliveryPublicKey));

            if (deliveryPublicKey.IsSet && deliveryPublicKey.Value == null)
                throw new ArgumentNullException(nameof(deliveryPublicKey), "Property is not nullable for class V2EncryptedDeliveryRequest.");

            return new V2EncryptedDeliveryRequest(deliveryPublicKey.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2EncryptedDeliveryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2EncryptedDeliveryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2EncryptedDeliveryRequest v2EncryptedDeliveryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2EncryptedDeliveryRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2EncryptedDeliveryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2EncryptedDeliveryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2EncryptedDeliveryRequest v2EncryptedDeliveryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2EncryptedDeliveryRequest.DeliveryPublicKey == null)
                throw new ArgumentNullException(nameof(v2EncryptedDeliveryRequest.DeliveryPublicKey), "Property is required for class V2EncryptedDeliveryRequest.");

            writer.WritePropertyName("delivery_public_key");
            JsonSerializer.Serialize(writer, v2EncryptedDeliveryRequest.DeliveryPublicKey, jsonSerializerOptions);
        }
    }
}
