// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2ImageRenderRequest
    /// </summary>
    public partial class V2ImageRenderRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2ImageRenderRequest" /> class.
        /// </summary>
        /// <param name="item">item</param>
        /// <param name="sceneId">sceneId</param>
        /// <param name="output">output</param>
        /// <param name="sceneRevision">sceneRevision</param>
        [JsonConstructor]
        public V2ImageRenderRequest(V2RenderItemRequest item, Guid sceneId, V2ImageRenderOutput output, Option<int?> sceneRevision = default)
        {
            Item = item;
            SceneId = sceneId;
            Output = output;
            SceneRevisionOption = sceneRevision;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Item
        /// </summary>
        [JsonPropertyName("item")]
        public V2RenderItemRequest Item { get; set; }

        /// <summary>
        /// Gets or Sets SceneId
        /// </summary>
        [JsonPropertyName("scene_id")]
        public Guid SceneId { get; set; }

        /// <summary>
        /// Gets or Sets Output
        /// </summary>
        [JsonPropertyName("output")]
        public V2ImageRenderOutput Output { get; set; }

        /// <summary>
        /// Used to track the state of SceneRevision
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SceneRevisionOption { get; private set; }

        /// <summary>
        /// Gets or Sets SceneRevision
        /// </summary>
        [JsonPropertyName("scene_revision")]
        public int? SceneRevision { get { return this.SceneRevisionOption.Value; } set { this.SceneRevisionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2ImageRenderRequest {\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("  SceneId: ").Append(SceneId).Append("\n");
            sb.Append("  Output: ").Append(Output).Append("\n");
            sb.Append("  SceneRevision: ").Append(SceneRevision).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SceneRevision (int) minimum
            if (this.SceneRevisionOption.IsSet && this.SceneRevisionOption.Value < (int)1)
            {
                yield return new ValidationResult("Invalid value for SceneRevision, must be a value greater than or equal to 1.", new [] { "SceneRevision" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2ImageRenderRequest" />
    /// </summary>
    public partial class V2ImageRenderRequestJsonConverter : JsonConverter<V2ImageRenderRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2ImageRenderRequestJsonConverter" /> class.
        /// </summary>
        public V2ImageRenderRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2ImageRenderRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2ImageRenderRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2RenderItemRequest?> item = default;
            Option<Guid?> sceneId = default;
            Option<V2ImageRenderOutput?> output = default;
            Option<int?> sceneRevision = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "item":
                            item = new Option<V2RenderItemRequest?>(JsonSerializer.Deserialize<V2RenderItemRequest>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scene_id":
                            sceneId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "output":
                            output = new Option<V2ImageRenderOutput?>(JsonSerializer.Deserialize<V2ImageRenderOutput>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scene_revision":
                            sceneRevision = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!item.IsSet)
                throw new ArgumentException("Property is required for class V2ImageRenderRequest.", nameof(item));

            if (!sceneId.IsSet)
                throw new ArgumentException("Property is required for class V2ImageRenderRequest.", nameof(sceneId));

            if (!output.IsSet)
                throw new ArgumentException("Property is required for class V2ImageRenderRequest.", nameof(output));

            if (item.IsSet && item.Value == null)
                throw new ArgumentNullException(nameof(item), "Property is not nullable for class V2ImageRenderRequest.");

            if (sceneId.IsSet && sceneId.Value == null)
                throw new ArgumentNullException(nameof(sceneId), "Property is not nullable for class V2ImageRenderRequest.");

            if (output.IsSet && output.Value == null)
                throw new ArgumentNullException(nameof(output), "Property is not nullable for class V2ImageRenderRequest.");

            if (sceneRevision.IsSet && sceneRevision.Value == null)
                throw new ArgumentNullException(nameof(sceneRevision), "Property is not nullable for class V2ImageRenderRequest.");

            return new V2ImageRenderRequest(item.Value!, sceneId.Value!.Value!, output.Value!, sceneRevision);
        }

        /// <summary>
        /// Serializes a <see cref="V2ImageRenderRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ImageRenderRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2ImageRenderRequest v2ImageRenderRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2ImageRenderRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2ImageRenderRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ImageRenderRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2ImageRenderRequest v2ImageRenderRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2ImageRenderRequest.Item == null)
                throw new ArgumentNullException(nameof(v2ImageRenderRequest.Item), "Property is required for class V2ImageRenderRequest.");

            if (v2ImageRenderRequest.Output == null)
                throw new ArgumentNullException(nameof(v2ImageRenderRequest.Output), "Property is required for class V2ImageRenderRequest.");

            writer.WritePropertyName("item");
            JsonSerializer.Serialize(writer, v2ImageRenderRequest.Item, jsonSerializerOptions);
            writer.WriteString("scene_id", v2ImageRenderRequest.SceneId);

            writer.WritePropertyName("output");
            JsonSerializer.Serialize(writer, v2ImageRenderRequest.Output, jsonSerializerOptions);
            if (v2ImageRenderRequest.SceneRevisionOption.IsSet)
                writer.WriteNumber("scene_revision", v2ImageRenderRequest.SceneRevisionOption.Value!.Value);
        }
    }
}
