// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2ImageRenderResult
    /// </summary>
    public partial class V2ImageRenderResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2ImageRenderResult" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="sha256">sha256</param>
        /// <param name="expiresAt">expiresAt</param>
        [JsonConstructor]
        public V2ImageRenderResult(string url, string sha256, DateTime expiresAt)
        {
            Url = url;
            Sha256 = sha256;
            ExpiresAt = expiresAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Sha256
        /// </summary>
        [JsonPropertyName("sha256")]
        public string Sha256 { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expires_at")]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2ImageRenderResult {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Sha256: ").Append(Sha256).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Url != null) {
                // Url (string) pattern
                Regex regexUrl = new Regex(@"^https://", RegexOptions.CultureInvariant);

                if (!regexUrl.Match(this.Url).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Url, must match a pattern of " + regexUrl, new [] { "Url" });
                }
            }

            if (this.Sha256 != null) {
                // Sha256 (string) pattern
                Regex regexSha256 = new Regex(@"^[0-9a-f]{64}$", RegexOptions.CultureInvariant);

                if (!regexSha256.Match(this.Sha256).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sha256, must match a pattern of " + regexSha256, new [] { "Sha256" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2ImageRenderResult" />
    /// </summary>
    public partial class V2ImageRenderResultJsonConverter : JsonConverter<V2ImageRenderResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2ImageRenderResultJsonConverter" /> class.
        /// </summary>
        public V2ImageRenderResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2ImageRenderResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2ImageRenderResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<string?> sha256 = default;
            Option<DateTime?> expiresAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sha256":
                            sha256 = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class V2ImageRenderResult.", nameof(url));

            if (!sha256.IsSet)
                throw new ArgumentException("Property is required for class V2ImageRenderResult.", nameof(sha256));

            if (!expiresAt.IsSet)
                throw new ArgumentException("Property is required for class V2ImageRenderResult.", nameof(expiresAt));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class V2ImageRenderResult.");

            if (sha256.IsSet && sha256.Value == null)
                throw new ArgumentNullException(nameof(sha256), "Property is not nullable for class V2ImageRenderResult.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class V2ImageRenderResult.");

            return new V2ImageRenderResult(url.Value!, sha256.Value!, expiresAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2ImageRenderResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ImageRenderResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2ImageRenderResult v2ImageRenderResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2ImageRenderResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2ImageRenderResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ImageRenderResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2ImageRenderResult v2ImageRenderResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2ImageRenderResult.Url == null)
                throw new ArgumentNullException(nameof(v2ImageRenderResult.Url), "Property is required for class V2ImageRenderResult.");

            if (v2ImageRenderResult.Sha256 == null)
                throw new ArgumentNullException(nameof(v2ImageRenderResult.Sha256), "Property is required for class V2ImageRenderResult.");

            writer.WriteString("url", v2ImageRenderResult.Url);

            writer.WriteString("sha256", v2ImageRenderResult.Sha256);

            writer.WriteString("expires_at", v2ImageRenderResult.ExpiresAt.ToString(ExpiresAtFormat));
        }
    }
}
