// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2InventorySnapshotAssetsInner
    /// </summary>
    public partial class V2InventorySnapshotAssetsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2InventorySnapshotAssetsInner" /> class.
        /// </summary>
        /// <param name="assetId">assetId</param>
        /// <param name="classId">classId</param>
        /// <param name="instanceId">instanceId</param>
        /// <param name="quantity">quantity</param>
        /// <param name="item">item</param>
        /// <param name="prices">prices</param>
        /// <param name="inspect">inspect</param>
        [JsonConstructor]
        public V2InventorySnapshotAssetsInner(string assetId, string classId, string instanceId, int quantity, V2InventoryCatalogItem item, List<Object> prices, Option<Object?> inspect = default)
        {
            AssetId = assetId;
            ClassId = classId;
            InstanceId = instanceId;
            Quantity = quantity;
            Item = item;
            Prices = prices;
            InspectOption = inspect;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("asset_id")]
        public string AssetId { get; set; }

        /// <summary>
        /// Gets or Sets ClassId
        /// </summary>
        [JsonPropertyName("class_id")]
        public string ClassId { get; set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [JsonPropertyName("instance_id")]
        public string InstanceId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Item
        /// </summary>
        [JsonPropertyName("item")]
        public V2InventoryCatalogItem Item { get; set; }

        /// <summary>
        /// Gets or Sets Prices
        /// </summary>
        [JsonPropertyName("prices")]
        public List<Object> Prices { get; set; }

        /// <summary>
        /// Used to track the state of Inspect
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> InspectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Inspect
        /// </summary>
        [JsonPropertyName("inspect")]
        public Object? Inspect { get { return this.InspectOption.Value; } set { this.InspectOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2InventorySnapshotAssetsInner {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  ClassId: ").Append(ClassId).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("  Prices: ").Append(Prices).Append("\n");
            sb.Append("  Inspect: ").Append(Inspect).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2InventorySnapshotAssetsInner" />
    /// </summary>
    public partial class V2InventorySnapshotAssetsInnerJsonConverter : JsonConverter<V2InventorySnapshotAssetsInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2InventorySnapshotAssetsInnerJsonConverter" /> class.
        /// </summary>
        public V2InventorySnapshotAssetsInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2InventorySnapshotAssetsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2InventorySnapshotAssetsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> assetId = default;
            Option<string?> classId = default;
            Option<string?> instanceId = default;
            Option<int?> quantity = default;
            Option<V2InventoryCatalogItem?> item = default;
            Option<List<Object>?> prices = default;
            Option<Object?> inspect = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "asset_id":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "class_id":
                            classId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "instance_id":
                            instanceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "quantity":
                            quantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "item":
                            item = new Option<V2InventoryCatalogItem?>(JsonSerializer.Deserialize<V2InventoryCatalogItem>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "prices":
                            prices = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "inspect":
                            inspect = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class V2InventorySnapshotAssetsInner.", nameof(assetId));

            if (!classId.IsSet)
                throw new ArgumentException("Property is required for class V2InventorySnapshotAssetsInner.", nameof(classId));

            if (!instanceId.IsSet)
                throw new ArgumentException("Property is required for class V2InventorySnapshotAssetsInner.", nameof(instanceId));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class V2InventorySnapshotAssetsInner.", nameof(quantity));

            if (!item.IsSet)
                throw new ArgumentException("Property is required for class V2InventorySnapshotAssetsInner.", nameof(item));

            if (!prices.IsSet)
                throw new ArgumentException("Property is required for class V2InventorySnapshotAssetsInner.", nameof(prices));

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            if (classId.IsSet && classId.Value == null)
                throw new ArgumentNullException(nameof(classId), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            if (instanceId.IsSet && instanceId.Value == null)
                throw new ArgumentNullException(nameof(instanceId), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            if (item.IsSet && item.Value == null)
                throw new ArgumentNullException(nameof(item), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            if (prices.IsSet && prices.Value == null)
                throw new ArgumentNullException(nameof(prices), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            if (inspect.IsSet && inspect.Value == null)
                throw new ArgumentNullException(nameof(inspect), "Property is not nullable for class V2InventorySnapshotAssetsInner.");

            return new V2InventorySnapshotAssetsInner(assetId.Value!, classId.Value!, instanceId.Value!, quantity.Value!.Value!, item.Value!, prices.Value!, inspect);
        }

        /// <summary>
        /// Serializes a <see cref="V2InventorySnapshotAssetsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2InventorySnapshotAssetsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2InventorySnapshotAssetsInner v2InventorySnapshotAssetsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2InventorySnapshotAssetsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2InventorySnapshotAssetsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2InventorySnapshotAssetsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2InventorySnapshotAssetsInner v2InventorySnapshotAssetsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2InventorySnapshotAssetsInner.AssetId == null)
                throw new ArgumentNullException(nameof(v2InventorySnapshotAssetsInner.AssetId), "Property is required for class V2InventorySnapshotAssetsInner.");

            if (v2InventorySnapshotAssetsInner.ClassId == null)
                throw new ArgumentNullException(nameof(v2InventorySnapshotAssetsInner.ClassId), "Property is required for class V2InventorySnapshotAssetsInner.");

            if (v2InventorySnapshotAssetsInner.InstanceId == null)
                throw new ArgumentNullException(nameof(v2InventorySnapshotAssetsInner.InstanceId), "Property is required for class V2InventorySnapshotAssetsInner.");

            if (v2InventorySnapshotAssetsInner.Item == null)
                throw new ArgumentNullException(nameof(v2InventorySnapshotAssetsInner.Item), "Property is required for class V2InventorySnapshotAssetsInner.");

            if (v2InventorySnapshotAssetsInner.Prices == null)
                throw new ArgumentNullException(nameof(v2InventorySnapshotAssetsInner.Prices), "Property is required for class V2InventorySnapshotAssetsInner.");

            if (v2InventorySnapshotAssetsInner.InspectOption.IsSet && v2InventorySnapshotAssetsInner.Inspect == null)
                throw new ArgumentNullException(nameof(v2InventorySnapshotAssetsInner.Inspect), "Property is required for class V2InventorySnapshotAssetsInner.");

            writer.WriteString("asset_id", v2InventorySnapshotAssetsInner.AssetId);

            writer.WriteString("class_id", v2InventorySnapshotAssetsInner.ClassId);

            writer.WriteString("instance_id", v2InventorySnapshotAssetsInner.InstanceId);

            writer.WriteNumber("quantity", v2InventorySnapshotAssetsInner.Quantity);

            writer.WritePropertyName("item");
            JsonSerializer.Serialize(writer, v2InventorySnapshotAssetsInner.Item, jsonSerializerOptions);
            writer.WritePropertyName("prices");
            JsonSerializer.Serialize(writer, v2InventorySnapshotAssetsInner.Prices, jsonSerializerOptions);
            if (v2InventorySnapshotAssetsInner.InspectOption.IsSet)
            {
                writer.WritePropertyName("inspect");
                JsonSerializer.Serialize(writer, v2InventorySnapshotAssetsInner.Inspect, jsonSerializerOptions);
            }
        }
    }
}
