// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2InstancePublication
    /// </summary>
    public partial class V2InstancePublication : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2InstancePublication" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="state">state</param>
        /// <param name="requestSha256">requestSha256</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="bundleId">bundleId</param>
        /// <param name="rendererBuildId">rendererBuildId</param>
        /// <param name="capabilities">capabilities</param>
        /// <param name="errorCode">limited customer-safe terminal code; never an exception or object-store detail.</param>
        [JsonConstructor]
        public V2InstancePublication(Guid id, StateEnum state, string requestSha256, DateTime createdAt, DateTime updatedAt, Option<string?> bundleId = default, Option<string?> rendererBuildId = default, Option<V2InstancePublicationCapabilities?> capabilities = default, Option<string?> errorCode = default)
        {
            Id = id;
            State = state;
            RequestSha256 = requestSha256;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            BundleIdOption = bundleId;
            RendererBuildIdOption = rendererBuildId;
            CapabilitiesOption = capabilities;
            ErrorCodeOption = errorCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines State
        /// </summary>
        public enum StateEnum
        {
            /// <summary>
            /// Enum Queued for value: queued
            /// </summary>
            Queued = 1,

            /// <summary>
            /// Enum Leased for value: leased
            /// </summary>
            Leased = 2,

            /// <summary>
            /// Enum Publishing for value: publishing
            /// </summary>
            Publishing = 3,

            /// <summary>
            /// Enum Succeeded for value: succeeded
            /// </summary>
            Succeeded = 4,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 5
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StateEnum StateEnumFromString(string value)
        {
            if (value.Equals("queued"))
                return StateEnum.Queued;

            if (value.Equals("leased"))
                return StateEnum.Leased;

            if (value.Equals("publishing"))
                return StateEnum.Publishing;

            if (value.Equals("succeeded"))
                return StateEnum.Succeeded;

            if (value.Equals("failed"))
                return StateEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StateEnum? StateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("queued"))
                return StateEnum.Queued;

            if (value.Equals("leased"))
                return StateEnum.Leased;

            if (value.Equals("publishing"))
                return StateEnum.Publishing;

            if (value.Equals("succeeded"))
                return StateEnum.Succeeded;

            if (value.Equals("failed"))
                return StateEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StateEnumToJsonValue(StateEnum value)
        {
            if (value == StateEnum.Queued)
                return "queued";

            if (value == StateEnum.Leased)
                return "leased";

            if (value == StateEnum.Publishing)
                return "publishing";

            if (value == StateEnum.Succeeded)
                return "succeeded";

            if (value == StateEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public StateEnum State { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets RequestSha256
        /// </summary>
        [JsonPropertyName("request_sha256")]
        public string RequestSha256 { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of BundleId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BundleIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets BundleId
        /// </summary>
        [JsonPropertyName("bundle_id")]
        public string? BundleId { get { return this.BundleIdOption.Value; } set { this.BundleIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RendererBuildId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RendererBuildIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets RendererBuildId
        /// </summary>
        [JsonPropertyName("renderer_build_id")]
        public string? RendererBuildId { get { return this.RendererBuildIdOption.Value; } set { this.RendererBuildIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Capabilities
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<V2InstancePublicationCapabilities?> CapabilitiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Capabilities
        /// </summary>
        [JsonPropertyName("capabilities")]
        public V2InstancePublicationCapabilities? Capabilities { get { return this.CapabilitiesOption.Value; } set { this.CapabilitiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorCodeOption { get; private set; }

        /// <summary>
        /// limited customer-safe terminal code; never an exception or object-store detail.
        /// </summary>
        /// <value>limited customer-safe terminal code; never an exception or object-store detail.</value>
        [JsonPropertyName("error_code")]
        public string? ErrorCode { get { return this.ErrorCodeOption.Value; } set { this.ErrorCodeOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2InstancePublication {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  RequestSha256: ").Append(RequestSha256).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  BundleId: ").Append(BundleId).Append("\n");
            sb.Append("  RendererBuildId: ").Append(RendererBuildId).Append("\n");
            sb.Append("  Capabilities: ").Append(Capabilities).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.RequestSha256 != null) {
                // RequestSha256 (string) pattern
                Regex regexRequestSha256 = new Regex(@"^[0-9a-f]{64}$", RegexOptions.CultureInvariant);

                if (!regexRequestSha256.Match(this.RequestSha256).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RequestSha256, must match a pattern of " + regexRequestSha256, new [] { "RequestSha256" });
                }
            }

            if (this.BundleIdOption.Value != null) {
                // BundleId (string) pattern
                Regex regexBundleId = new Regex(@"^[0-9a-f]{64}$", RegexOptions.CultureInvariant);

                if (this.BundleIdOption.Value != null &&!regexBundleId.Match(this.BundleIdOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BundleId, must match a pattern of " + regexBundleId, new [] { "BundleId" });
                }
            }

            if (this.RendererBuildIdOption.Value != null) {
                // RendererBuildId (string) pattern
                Regex regexRendererBuildId = new Regex(@"^[0-9a-f]{64}$", RegexOptions.CultureInvariant);

                if (this.RendererBuildIdOption.Value != null &&!regexRendererBuildId.Match(this.RendererBuildIdOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RendererBuildId, must match a pattern of " + regexRendererBuildId, new [] { "RendererBuildId" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2InstancePublication" />
    /// </summary>
    public partial class V2InstancePublicationJsonConverter : JsonConverter<V2InstancePublication>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2InstancePublicationJsonConverter" /> class.
        /// </summary>
        public V2InstancePublicationJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2InstancePublication" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2InstancePublication Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<V2InstancePublication.StateEnum?> state = default;
            Option<string?> requestSha256 = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> bundleId = default;
            Option<string?> rendererBuildId = default;
            Option<V2InstancePublicationCapabilities?> capabilities = default;
            Option<string?> errorCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                            {
                                V2InstancePublication.StateEnum? stateValue = V2InstancePublication.StateEnumFromStringOrDefault(stateRawValue);
                                if (stateValue == null)
                                    throw new JsonException();
                                state = new Option<V2InstancePublication.StateEnum?>(stateValue);
                            }
                            break;
                        case "request_sha256":
                            requestSha256 = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "bundle_id":
                            bundleId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "renderer_build_id":
                            rendererBuildId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "capabilities":
                            capabilities = new Option<V2InstancePublicationCapabilities?>(JsonSerializer.Deserialize<V2InstancePublicationCapabilities>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error_code":
                            errorCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class V2InstancePublication.", nameof(id));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class V2InstancePublication.", nameof(state));

            if (!requestSha256.IsSet)
                throw new ArgumentException("Property is required for class V2InstancePublication.", nameof(requestSha256));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class V2InstancePublication.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class V2InstancePublication.", nameof(updatedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class V2InstancePublication.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class V2InstancePublication.");

            if (requestSha256.IsSet && requestSha256.Value == null)
                throw new ArgumentNullException(nameof(requestSha256), "Property is not nullable for class V2InstancePublication.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class V2InstancePublication.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class V2InstancePublication.");

            if (bundleId.IsSet && bundleId.Value == null)
                throw new ArgumentNullException(nameof(bundleId), "Property is not nullable for class V2InstancePublication.");

            if (rendererBuildId.IsSet && rendererBuildId.Value == null)
                throw new ArgumentNullException(nameof(rendererBuildId), "Property is not nullable for class V2InstancePublication.");

            if (capabilities.IsSet && capabilities.Value == null)
                throw new ArgumentNullException(nameof(capabilities), "Property is not nullable for class V2InstancePublication.");

            if (errorCode.IsSet && errorCode.Value == null)
                throw new ArgumentNullException(nameof(errorCode), "Property is not nullable for class V2InstancePublication.");

            return new V2InstancePublication(id.Value!.Value!, state.Value!.Value!, requestSha256.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, bundleId, rendererBuildId, capabilities, errorCode);
        }

        /// <summary>
        /// Serializes a <see cref="V2InstancePublication" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2InstancePublication"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2InstancePublication v2InstancePublication, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2InstancePublication, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2InstancePublication" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2InstancePublication"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2InstancePublication v2InstancePublication, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2InstancePublication.RequestSha256 == null)
                throw new ArgumentNullException(nameof(v2InstancePublication.RequestSha256), "Property is required for class V2InstancePublication.");

            if (v2InstancePublication.BundleIdOption.IsSet && v2InstancePublication.BundleId == null)
                throw new ArgumentNullException(nameof(v2InstancePublication.BundleId), "Property is required for class V2InstancePublication.");

            if (v2InstancePublication.RendererBuildIdOption.IsSet && v2InstancePublication.RendererBuildId == null)
                throw new ArgumentNullException(nameof(v2InstancePublication.RendererBuildId), "Property is required for class V2InstancePublication.");

            if (v2InstancePublication.CapabilitiesOption.IsSet && v2InstancePublication.Capabilities == null)
                throw new ArgumentNullException(nameof(v2InstancePublication.Capabilities), "Property is required for class V2InstancePublication.");

            if (v2InstancePublication.ErrorCodeOption.IsSet && v2InstancePublication.ErrorCode == null)
                throw new ArgumentNullException(nameof(v2InstancePublication.ErrorCode), "Property is required for class V2InstancePublication.");

            writer.WriteString("id", v2InstancePublication.Id);

            var stateRawValue = V2InstancePublication.StateEnumToJsonValue(v2InstancePublication.State);
            writer.WriteString("state", stateRawValue);
            writer.WriteString("request_sha256", v2InstancePublication.RequestSha256);

            writer.WriteString("created_at", v2InstancePublication.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updated_at", v2InstancePublication.UpdatedAt.ToString(UpdatedAtFormat));

            if (v2InstancePublication.BundleIdOption.IsSet)
                writer.WriteString("bundle_id", v2InstancePublication.BundleId);

            if (v2InstancePublication.RendererBuildIdOption.IsSet)
                writer.WriteString("renderer_build_id", v2InstancePublication.RendererBuildId);

            if (v2InstancePublication.CapabilitiesOption.IsSet)
            {
                writer.WritePropertyName("capabilities");
                JsonSerializer.Serialize(writer, v2InstancePublication.Capabilities, jsonSerializerOptions);
            }
            if (v2InstancePublication.ErrorCodeOption.IsSet)
                writer.WriteString("error_code", v2InstancePublication.ErrorCode);
        }
    }
}
