// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2InventoryHistoryPage
    /// </summary>
    public partial class V2InventoryHistoryPage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2InventoryHistoryPage" /> class.
        /// </summary>
        /// <param name="snapshots">snapshots</param>
        /// <param name="count">count</param>
        /// <param name="nextCursor">nextCursor</param>
        [JsonConstructor]
        public V2InventoryHistoryPage(List<V2InventoryHistoryEntry> snapshots, int count, Option<string?> nextCursor = default)
        {
            Snapshots = snapshots;
            Count = count;
            NextCursorOption = nextCursor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Snapshots
        /// </summary>
        [JsonPropertyName("snapshots")]
        public List<V2InventoryHistoryEntry> Snapshots { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [JsonPropertyName("count")]
        public int Count { get; set; }

        /// <summary>
        /// Used to track the state of NextCursor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NextCursorOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [JsonPropertyName("next_cursor")]
        public string? NextCursor { get { return this.NextCursorOption.Value; } set { this.NextCursorOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2InventoryHistoryPage {\n");
            sb.Append("  Snapshots: ").Append(Snapshots).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Count (int) minimum
            if (this.Count < (int)0)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value greater than or equal to 0.", new [] { "Count" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2InventoryHistoryPage" />
    /// </summary>
    public partial class V2InventoryHistoryPageJsonConverter : JsonConverter<V2InventoryHistoryPage>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2InventoryHistoryPageJsonConverter" /> class.
        /// </summary>
        public V2InventoryHistoryPageJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2InventoryHistoryPage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2InventoryHistoryPage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<V2InventoryHistoryEntry>?> snapshots = default;
            Option<int?> count = default;
            Option<string?> nextCursor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "snapshots":
                            snapshots = new Option<List<V2InventoryHistoryEntry>?>(JsonSerializer.Deserialize<List<V2InventoryHistoryEntry>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "next_cursor":
                            nextCursor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!snapshots.IsSet)
                throw new ArgumentException("Property is required for class V2InventoryHistoryPage.", nameof(snapshots));

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class V2InventoryHistoryPage.", nameof(count));

            if (snapshots.IsSet && snapshots.Value == null)
                throw new ArgumentNullException(nameof(snapshots), "Property is not nullable for class V2InventoryHistoryPage.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class V2InventoryHistoryPage.");

            if (nextCursor.IsSet && nextCursor.Value == null)
                throw new ArgumentNullException(nameof(nextCursor), "Property is not nullable for class V2InventoryHistoryPage.");

            return new V2InventoryHistoryPage(snapshots.Value!, count.Value!.Value!, nextCursor);
        }

        /// <summary>
        /// Serializes a <see cref="V2InventoryHistoryPage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2InventoryHistoryPage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2InventoryHistoryPage v2InventoryHistoryPage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2InventoryHistoryPage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2InventoryHistoryPage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2InventoryHistoryPage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2InventoryHistoryPage v2InventoryHistoryPage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2InventoryHistoryPage.Snapshots == null)
                throw new ArgumentNullException(nameof(v2InventoryHistoryPage.Snapshots), "Property is required for class V2InventoryHistoryPage.");

            if (v2InventoryHistoryPage.NextCursorOption.IsSet && v2InventoryHistoryPage.NextCursor == null)
                throw new ArgumentNullException(nameof(v2InventoryHistoryPage.NextCursor), "Property is required for class V2InventoryHistoryPage.");

            writer.WritePropertyName("snapshots");
            JsonSerializer.Serialize(writer, v2InventoryHistoryPage.Snapshots, jsonSerializerOptions);
            writer.WriteNumber("count", v2InventoryHistoryPage.Count);

            if (v2InventoryHistoryPage.NextCursorOption.IsSet)
                writer.WriteString("next_cursor", v2InventoryHistoryPage.NextCursor);
        }
    }
}
