// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2ItemCatalogQueryReceipt
    /// </summary>
    public partial class V2ItemCatalogQueryReceipt : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2ItemCatalogQueryReceipt" /> class.
        /// </summary>
        /// <param name="definitionIndex">definitionIndex</param>
        /// <param name="stattrak">stattrak</param>
        /// <param name="souvenir">souvenir</param>
        /// <param name="paintIndex">paintIndex</param>
        /// <param name="exterior">exterior</param>
        [JsonConstructor]
        public V2ItemCatalogQueryReceipt(int definitionIndex, bool stattrak, bool souvenir, Option<int?> paintIndex = default, Option<ExteriorEnum?> exterior = default)
        {
            DefinitionIndex = definitionIndex;
            Stattrak = stattrak;
            Souvenir = souvenir;
            PaintIndexOption = paintIndex;
            ExteriorOption = exterior;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Exterior
        /// </summary>
        public enum ExteriorEnum
        {
            /// <summary>
            /// Enum FactoryNew for value: Factory New
            /// </summary>
            FactoryNew = 1,

            /// <summary>
            /// Enum MinimalWear for value: Minimal Wear
            /// </summary>
            MinimalWear = 2,

            /// <summary>
            /// Enum FieldTested for value: Field-Tested
            /// </summary>
            FieldTested = 3,

            /// <summary>
            /// Enum WellWorn for value: Well-Worn
            /// </summary>
            WellWorn = 4,

            /// <summary>
            /// Enum BattleScarred for value: Battle-Scarred
            /// </summary>
            BattleScarred = 5
        }

        /// <summary>
        /// Returns a <see cref="ExteriorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ExteriorEnum ExteriorEnumFromString(string value)
        {
            if (value.Equals("Factory New"))
                return ExteriorEnum.FactoryNew;

            if (value.Equals("Minimal Wear"))
                return ExteriorEnum.MinimalWear;

            if (value.Equals("Field-Tested"))
                return ExteriorEnum.FieldTested;

            if (value.Equals("Well-Worn"))
                return ExteriorEnum.WellWorn;

            if (value.Equals("Battle-Scarred"))
                return ExteriorEnum.BattleScarred;

            throw new NotImplementedException($"Could not convert value to type ExteriorEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ExteriorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ExteriorEnum? ExteriorEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Factory New"))
                return ExteriorEnum.FactoryNew;

            if (value.Equals("Minimal Wear"))
                return ExteriorEnum.MinimalWear;

            if (value.Equals("Field-Tested"))
                return ExteriorEnum.FieldTested;

            if (value.Equals("Well-Worn"))
                return ExteriorEnum.WellWorn;

            if (value.Equals("Battle-Scarred"))
                return ExteriorEnum.BattleScarred;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ExteriorEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ExteriorEnumToJsonValue(ExteriorEnum? value)
        {
            if (value == ExteriorEnum.FactoryNew)
                return "Factory New";

            if (value == ExteriorEnum.MinimalWear)
                return "Minimal Wear";

            if (value == ExteriorEnum.FieldTested)
                return "Field-Tested";

            if (value == ExteriorEnum.WellWorn)
                return "Well-Worn";

            if (value == ExteriorEnum.BattleScarred)
                return "Battle-Scarred";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Exterior
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ExteriorEnum?> ExteriorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Exterior
        /// </summary>
        [JsonPropertyName("exterior")]
        public ExteriorEnum? Exterior { get { return this.ExteriorOption.Value; } set { this.ExteriorOption = new(value); } }

        /// <summary>
        /// Gets or Sets DefinitionIndex
        /// </summary>
        [JsonPropertyName("definition_index")]
        public int DefinitionIndex { get; set; }

        /// <summary>
        /// Gets or Sets Stattrak
        /// </summary>
        [JsonPropertyName("stattrak")]
        public bool Stattrak { get; set; }

        /// <summary>
        /// Gets or Sets Souvenir
        /// </summary>
        [JsonPropertyName("souvenir")]
        public bool Souvenir { get; set; }

        /// <summary>
        /// Used to track the state of PaintIndex
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PaintIndexOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaintIndex
        /// </summary>
        [JsonPropertyName("paint_index")]
        public int? PaintIndex { get { return this.PaintIndexOption.Value; } set { this.PaintIndexOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2ItemCatalogQueryReceipt {\n");
            sb.Append("  DefinitionIndex: ").Append(DefinitionIndex).Append("\n");
            sb.Append("  Stattrak: ").Append(Stattrak).Append("\n");
            sb.Append("  Souvenir: ").Append(Souvenir).Append("\n");
            sb.Append("  PaintIndex: ").Append(PaintIndex).Append("\n");
            sb.Append("  Exterior: ").Append(Exterior).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DefinitionIndex (int) minimum
            if (this.DefinitionIndex < (int)1)
            {
                yield return new ValidationResult("Invalid value for DefinitionIndex, must be a value greater than or equal to 1.", new [] { "DefinitionIndex" });
            }

            // PaintIndex (int) minimum
            if (this.PaintIndexOption.IsSet && this.PaintIndexOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for PaintIndex, must be a value greater than or equal to 0.", new [] { "PaintIndex" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2ItemCatalogQueryReceipt" />
    /// </summary>
    public partial class V2ItemCatalogQueryReceiptJsonConverter : JsonConverter<V2ItemCatalogQueryReceipt>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2ItemCatalogQueryReceiptJsonConverter" /> class.
        /// </summary>
        public V2ItemCatalogQueryReceiptJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2ItemCatalogQueryReceipt" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2ItemCatalogQueryReceipt Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> definitionIndex = default;
            Option<bool?> stattrak = default;
            Option<bool?> souvenir = default;
            Option<int?> paintIndex = default;
            Option<V2ItemCatalogQueryReceipt.ExteriorEnum?> exterior = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "definition_index":
                            definitionIndex = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "stattrak":
                            stattrak = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "souvenir":
                            souvenir = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "paint_index":
                            paintIndex = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "exterior":
                            string? exteriorRawValue = utf8JsonReader.GetString();
                            if (exteriorRawValue != null)
                            {
                                V2ItemCatalogQueryReceipt.ExteriorEnum? exteriorValue = V2ItemCatalogQueryReceipt.ExteriorEnumFromStringOrDefault(exteriorRawValue);
                                if (exteriorValue == null)
                                    throw new JsonException();
                                exterior = new Option<V2ItemCatalogQueryReceipt.ExteriorEnum?>(exteriorValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!definitionIndex.IsSet)
                throw new ArgumentException("Property is required for class V2ItemCatalogQueryReceipt.", nameof(definitionIndex));

            if (!stattrak.IsSet)
                throw new ArgumentException("Property is required for class V2ItemCatalogQueryReceipt.", nameof(stattrak));

            if (!souvenir.IsSet)
                throw new ArgumentException("Property is required for class V2ItemCatalogQueryReceipt.", nameof(souvenir));

            if (definitionIndex.IsSet && definitionIndex.Value == null)
                throw new ArgumentNullException(nameof(definitionIndex), "Property is not nullable for class V2ItemCatalogQueryReceipt.");

            if (stattrak.IsSet && stattrak.Value == null)
                throw new ArgumentNullException(nameof(stattrak), "Property is not nullable for class V2ItemCatalogQueryReceipt.");

            if (souvenir.IsSet && souvenir.Value == null)
                throw new ArgumentNullException(nameof(souvenir), "Property is not nullable for class V2ItemCatalogQueryReceipt.");

            if (paintIndex.IsSet && paintIndex.Value == null)
                throw new ArgumentNullException(nameof(paintIndex), "Property is not nullable for class V2ItemCatalogQueryReceipt.");

            if (exterior.IsSet && exterior.Value == null)
                throw new ArgumentNullException(nameof(exterior), "Property is not nullable for class V2ItemCatalogQueryReceipt.");

            return new V2ItemCatalogQueryReceipt(definitionIndex.Value!.Value!, stattrak.Value!.Value!, souvenir.Value!.Value!, paintIndex, exterior);
        }

        /// <summary>
        /// Serializes a <see cref="V2ItemCatalogQueryReceipt" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ItemCatalogQueryReceipt"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2ItemCatalogQueryReceipt v2ItemCatalogQueryReceipt, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2ItemCatalogQueryReceipt, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2ItemCatalogQueryReceipt" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ItemCatalogQueryReceipt"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2ItemCatalogQueryReceipt v2ItemCatalogQueryReceipt, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("definition_index", v2ItemCatalogQueryReceipt.DefinitionIndex);

            writer.WriteBoolean("stattrak", v2ItemCatalogQueryReceipt.Stattrak);

            writer.WriteBoolean("souvenir", v2ItemCatalogQueryReceipt.Souvenir);

            if (v2ItemCatalogQueryReceipt.PaintIndexOption.IsSet)
                writer.WriteNumber("paint_index", v2ItemCatalogQueryReceipt.PaintIndexOption.Value!.Value);

            var exteriorRawValue = V2ItemCatalogQueryReceipt.ExteriorEnumToJsonValue(v2ItemCatalogQueryReceipt.ExteriorOption.Value!.Value);
            writer.WriteString("exterior", exteriorRawValue);
        }
    }
}
