// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2ListWebhookDeliveriesResponse
    /// </summary>
    public partial class V2ListWebhookDeliveriesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2ListWebhookDeliveriesResponse" /> class.
        /// </summary>
        /// <param name="deliveries">deliveries</param>
        [JsonConstructor]
        public V2ListWebhookDeliveriesResponse(Option<List<V2WebhookDelivery>?> deliveries = default)
        {
            DeliveriesOption = deliveries;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Deliveries
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<V2WebhookDelivery>?> DeliveriesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Deliveries
        /// </summary>
        [JsonPropertyName("deliveries")]
        public List<V2WebhookDelivery>? Deliveries { get { return this.DeliveriesOption.Value; } set { this.DeliveriesOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2ListWebhookDeliveriesResponse {\n");
            sb.Append("  Deliveries: ").Append(Deliveries).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2ListWebhookDeliveriesResponse" />
    /// </summary>
    public partial class V2ListWebhookDeliveriesResponseJsonConverter : JsonConverter<V2ListWebhookDeliveriesResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2ListWebhookDeliveriesResponseJsonConverter" /> class.
        /// </summary>
        public V2ListWebhookDeliveriesResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2ListWebhookDeliveriesResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2ListWebhookDeliveriesResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<V2WebhookDelivery>?> deliveries = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "deliveries":
                            deliveries = new Option<List<V2WebhookDelivery>?>(JsonSerializer.Deserialize<List<V2WebhookDelivery>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (deliveries.IsSet && deliveries.Value == null)
                throw new ArgumentNullException(nameof(deliveries), "Property is not nullable for class V2ListWebhookDeliveriesResponse.");

            return new V2ListWebhookDeliveriesResponse(deliveries);
        }

        /// <summary>
        /// Serializes a <see cref="V2ListWebhookDeliveriesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ListWebhookDeliveriesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2ListWebhookDeliveriesResponse v2ListWebhookDeliveriesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2ListWebhookDeliveriesResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2ListWebhookDeliveriesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2ListWebhookDeliveriesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2ListWebhookDeliveriesResponse v2ListWebhookDeliveriesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2ListWebhookDeliveriesResponse.DeliveriesOption.IsSet && v2ListWebhookDeliveriesResponse.Deliveries == null)
                throw new ArgumentNullException(nameof(v2ListWebhookDeliveriesResponse.Deliveries), "Property is required for class V2ListWebhookDeliveriesResponse.");

            if (v2ListWebhookDeliveriesResponse.DeliveriesOption.IsSet)
            {
                writer.WritePropertyName("deliveries");
                JsonSerializer.Serialize(writer, v2ListWebhookDeliveriesResponse.Deliveries, jsonSerializerOptions);
            }
        }
    }
}
