// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2MarketListingInspectRequest
    /// </summary>
    public partial class V2MarketListingInspectRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2MarketListingInspectRequest" /> class.
        /// </summary>
        /// <param name="marketHashName">marketHashName</param>
        /// <param name="marketListingId">marketListingId</param>
        [JsonConstructor]
        public V2MarketListingInspectRequest(string marketHashName, string marketListingId)
        {
            MarketHashName = marketHashName;
            MarketListingId = marketListingId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets MarketHashName
        /// </summary>
        [JsonPropertyName("market_hash_name")]
        public string MarketHashName { get; set; }

        /// <summary>
        /// Gets or Sets MarketListingId
        /// </summary>
        [JsonPropertyName("market_listing_id")]
        public string MarketListingId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2MarketListingInspectRequest {\n");
            sb.Append("  MarketHashName: ").Append(MarketHashName).Append("\n");
            sb.Append("  MarketListingId: ").Append(MarketListingId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MarketHashName (string) maxLength
            if (this.MarketHashName != null && this.MarketHashName.Length > 512)
            {
                yield return new ValidationResult("Invalid value for MarketHashName, length must be less than 512.", new [] { "MarketHashName" });
            }

            // MarketHashName (string) minLength
            if (this.MarketHashName != null && this.MarketHashName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for MarketHashName, length must be greater than 1.", new [] { "MarketHashName" });
            }

            if (this.MarketListingId != null) {
                // MarketListingId (string) pattern
                Regex regexMarketListingId = new Regex(@"^[1-9][0-9]{0,19}$", RegexOptions.CultureInvariant);

                if (!regexMarketListingId.Match(this.MarketListingId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MarketListingId, must match a pattern of " + regexMarketListingId, new [] { "MarketListingId" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2MarketListingInspectRequest" />
    /// </summary>
    public partial class V2MarketListingInspectRequestJsonConverter : JsonConverter<V2MarketListingInspectRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2MarketListingInspectRequestJsonConverter" /> class.
        /// </summary>
        public V2MarketListingInspectRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2MarketListingInspectRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2MarketListingInspectRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> marketHashName = default;
            Option<string?> marketListingId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "market_hash_name":
                            marketHashName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "market_listing_id":
                            marketListingId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!marketHashName.IsSet)
                throw new ArgumentException("Property is required for class V2MarketListingInspectRequest.", nameof(marketHashName));

            if (!marketListingId.IsSet)
                throw new ArgumentException("Property is required for class V2MarketListingInspectRequest.", nameof(marketListingId));

            if (marketHashName.IsSet && marketHashName.Value == null)
                throw new ArgumentNullException(nameof(marketHashName), "Property is not nullable for class V2MarketListingInspectRequest.");

            if (marketListingId.IsSet && marketListingId.Value == null)
                throw new ArgumentNullException(nameof(marketListingId), "Property is not nullable for class V2MarketListingInspectRequest.");

            return new V2MarketListingInspectRequest(marketHashName.Value!, marketListingId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2MarketListingInspectRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2MarketListingInspectRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2MarketListingInspectRequest v2MarketListingInspectRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2MarketListingInspectRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2MarketListingInspectRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2MarketListingInspectRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2MarketListingInspectRequest v2MarketListingInspectRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2MarketListingInspectRequest.MarketHashName == null)
                throw new ArgumentNullException(nameof(v2MarketListingInspectRequest.MarketHashName), "Property is required for class V2MarketListingInspectRequest.");

            if (v2MarketListingInspectRequest.MarketListingId == null)
                throw new ArgumentNullException(nameof(v2MarketListingInspectRequest.MarketListingId), "Property is required for class V2MarketListingInspectRequest.");

            writer.WriteString("market_hash_name", v2MarketListingInspectRequest.MarketHashName);

            writer.WriteString("market_listing_id", v2MarketListingInspectRequest.MarketListingId);
        }
    }
}
