// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2MarketIndexComparison
    /// </summary>
    public partial class V2MarketIndexComparison : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2MarketIndexComparison" /> class.
        /// </summary>
        /// <param name="game">game</param>
        /// <param name="marketplace">marketplace</param>
        /// <param name="segmentDimension">segmentDimension</param>
        /// <param name="methodologyVersion">methodologyVersion</param>
        /// <param name="granularity">granularity</param>
        /// <param name="series">series</param>
        /// <param name="count">count</param>
        /// <param name="from">from</param>
        /// <param name="to">to</param>
        [JsonConstructor]
        public V2MarketIndexComparison(GameEnum game, MarketplaceEnum marketplace, SegmentDimensionEnum segmentDimension, MethodologyVersionEnum methodologyVersion, GranularityEnum granularity, List<V2MarketIndexComparisonSeries> series, int count, Option<DateTime?> from = default, Option<DateTime?> to = default)
        {
            Game = game;
            Marketplace = marketplace;
            SegmentDimension = segmentDimension;
            MethodologyVersion = methodologyVersion;
            Granularity = granularity;
            Series = series;
            Count = count;
            FromOption = from;
            ToOption = to;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Game
        /// </summary>
        public enum GameEnum
        {
            /// <summary>
            /// Enum Cs2 for value: cs2
            /// </summary>
            Cs2 = 1
        }

        /// <summary>
        /// Returns a <see cref="GameEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static GameEnum GameEnumFromString(string value)
        {
            if (value.Equals("cs2"))
                return GameEnum.Cs2;

            throw new NotImplementedException($"Could not convert value to type GameEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="GameEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GameEnum? GameEnumFromStringOrDefault(string value)
        {
            if (value.Equals("cs2"))
                return GameEnum.Cs2;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="GameEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string GameEnumToJsonValue(GameEnum value)
        {
            if (value == GameEnum.Cs2)
                return "cs2";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Game
        /// </summary>
        [JsonPropertyName("game")]
        public GameEnum Game { get; set; }

        /// <summary>
        /// Defines Marketplace
        /// </summary>
        public enum MarketplaceEnum
        {
            /// <summary>
            /// Enum Steam for value: steam
            /// </summary>
            Steam = 1,

            /// <summary>
            /// Enum Skinport for value: skinport
            /// </summary>
            Skinport = 2,

            /// <summary>
            /// Enum Buff for value: buff
            /// </summary>
            Buff = 3,

            /// <summary>
            /// Enum Youpin for value: youpin
            /// </summary>
            Youpin = 4,

            /// <summary>
            /// Enum Csfloat for value: csfloat
            /// </summary>
            Csfloat = 5
        }

        /// <summary>
        /// Returns a <see cref="MarketplaceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static MarketplaceEnum MarketplaceEnumFromString(string value)
        {
            if (value.Equals("steam"))
                return MarketplaceEnum.Steam;

            if (value.Equals("skinport"))
                return MarketplaceEnum.Skinport;

            if (value.Equals("buff"))
                return MarketplaceEnum.Buff;

            if (value.Equals("youpin"))
                return MarketplaceEnum.Youpin;

            if (value.Equals("csfloat"))
                return MarketplaceEnum.Csfloat;

            throw new NotImplementedException($"Could not convert value to type MarketplaceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="MarketplaceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MarketplaceEnum? MarketplaceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("steam"))
                return MarketplaceEnum.Steam;

            if (value.Equals("skinport"))
                return MarketplaceEnum.Skinport;

            if (value.Equals("buff"))
                return MarketplaceEnum.Buff;

            if (value.Equals("youpin"))
                return MarketplaceEnum.Youpin;

            if (value.Equals("csfloat"))
                return MarketplaceEnum.Csfloat;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MarketplaceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string MarketplaceEnumToJsonValue(MarketplaceEnum value)
        {
            if (value == MarketplaceEnum.Steam)
                return "steam";

            if (value == MarketplaceEnum.Skinport)
                return "skinport";

            if (value == MarketplaceEnum.Buff)
                return "buff";

            if (value == MarketplaceEnum.Youpin)
                return "youpin";

            if (value == MarketplaceEnum.Csfloat)
                return "csfloat";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Marketplace
        /// </summary>
        [JsonPropertyName("marketplace")]
        public MarketplaceEnum Marketplace { get; set; }

        /// <summary>
        /// Defines SegmentDimension
        /// </summary>
        public enum SegmentDimensionEnum
        {
            /// <summary>
            /// Enum Type for value: type
            /// </summary>
            Type = 1,

            /// <summary>
            /// Enum Weapon for value: weapon
            /// </summary>
            Weapon = 2,

            /// <summary>
            /// Enum Rarity for value: rarity
            /// </summary>
            Rarity = 3,

            /// <summary>
            /// Enum Exterior for value: exterior
            /// </summary>
            Exterior = 4,

            /// <summary>
            /// Enum Stattrak for value: stattrak
            /// </summary>
            Stattrak = 5,

            /// <summary>
            /// Enum Souvenir for value: souvenir
            /// </summary>
            Souvenir = 6,

            /// <summary>
            /// Enum Phase for value: phase
            /// </summary>
            Phase = 7,

            /// <summary>
            /// Enum Collection for value: collection
            /// </summary>
            Collection = 8
        }

        /// <summary>
        /// Returns a <see cref="SegmentDimensionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SegmentDimensionEnum SegmentDimensionEnumFromString(string value)
        {
            if (value.Equals("type"))
                return SegmentDimensionEnum.Type;

            if (value.Equals("weapon"))
                return SegmentDimensionEnum.Weapon;

            if (value.Equals("rarity"))
                return SegmentDimensionEnum.Rarity;

            if (value.Equals("exterior"))
                return SegmentDimensionEnum.Exterior;

            if (value.Equals("stattrak"))
                return SegmentDimensionEnum.Stattrak;

            if (value.Equals("souvenir"))
                return SegmentDimensionEnum.Souvenir;

            if (value.Equals("phase"))
                return SegmentDimensionEnum.Phase;

            if (value.Equals("collection"))
                return SegmentDimensionEnum.Collection;

            throw new NotImplementedException($"Could not convert value to type SegmentDimensionEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SegmentDimensionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SegmentDimensionEnum? SegmentDimensionEnumFromStringOrDefault(string value)
        {
            if (value.Equals("type"))
                return SegmentDimensionEnum.Type;

            if (value.Equals("weapon"))
                return SegmentDimensionEnum.Weapon;

            if (value.Equals("rarity"))
                return SegmentDimensionEnum.Rarity;

            if (value.Equals("exterior"))
                return SegmentDimensionEnum.Exterior;

            if (value.Equals("stattrak"))
                return SegmentDimensionEnum.Stattrak;

            if (value.Equals("souvenir"))
                return SegmentDimensionEnum.Souvenir;

            if (value.Equals("phase"))
                return SegmentDimensionEnum.Phase;

            if (value.Equals("collection"))
                return SegmentDimensionEnum.Collection;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SegmentDimensionEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SegmentDimensionEnumToJsonValue(SegmentDimensionEnum value)
        {
            if (value == SegmentDimensionEnum.Type)
                return "type";

            if (value == SegmentDimensionEnum.Weapon)
                return "weapon";

            if (value == SegmentDimensionEnum.Rarity)
                return "rarity";

            if (value == SegmentDimensionEnum.Exterior)
                return "exterior";

            if (value == SegmentDimensionEnum.Stattrak)
                return "stattrak";

            if (value == SegmentDimensionEnum.Souvenir)
                return "souvenir";

            if (value == SegmentDimensionEnum.Phase)
                return "phase";

            if (value == SegmentDimensionEnum.Collection)
                return "collection";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets SegmentDimension
        /// </summary>
        [JsonPropertyName("segment_dimension")]
        public SegmentDimensionEnum SegmentDimension { get; set; }

        /// <summary>
        /// Defines MethodologyVersion
        /// </summary>
        public enum MethodologyVersionEnum
        {
            /// <summary>
            /// Enum Cs2ChainEqualWeightV1 for value: cs2.chain-equal-weight.v1
            /// </summary>
            Cs2ChainEqualWeightV1 = 1
        }

        /// <summary>
        /// Returns a <see cref="MethodologyVersionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static MethodologyVersionEnum MethodologyVersionEnumFromString(string value)
        {
            if (value.Equals("cs2.chain-equal-weight.v1"))
                return MethodologyVersionEnum.Cs2ChainEqualWeightV1;

            throw new NotImplementedException($"Could not convert value to type MethodologyVersionEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="MethodologyVersionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MethodologyVersionEnum? MethodologyVersionEnumFromStringOrDefault(string value)
        {
            if (value.Equals("cs2.chain-equal-weight.v1"))
                return MethodologyVersionEnum.Cs2ChainEqualWeightV1;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MethodologyVersionEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string MethodologyVersionEnumToJsonValue(MethodologyVersionEnum value)
        {
            if (value == MethodologyVersionEnum.Cs2ChainEqualWeightV1)
                return "cs2.chain-equal-weight.v1";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets MethodologyVersion
        /// </summary>
        [JsonPropertyName("methodology_version")]
        public MethodologyVersionEnum MethodologyVersion { get; set; }

        /// <summary>
        /// Defines Granularity
        /// </summary>
        public enum GranularityEnum
        {
            /// <summary>
            /// Enum Daily for value: daily
            /// </summary>
            Daily = 1,

            /// <summary>
            /// Enum Weekly for value: weekly
            /// </summary>
            Weekly = 2,

            /// <summary>
            /// Enum Monthly for value: monthly
            /// </summary>
            Monthly = 3
        }

        /// <summary>
        /// Returns a <see cref="GranularityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static GranularityEnum GranularityEnumFromString(string value)
        {
            if (value.Equals("daily"))
                return GranularityEnum.Daily;

            if (value.Equals("weekly"))
                return GranularityEnum.Weekly;

            if (value.Equals("monthly"))
                return GranularityEnum.Monthly;

            throw new NotImplementedException($"Could not convert value to type GranularityEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="GranularityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GranularityEnum? GranularityEnumFromStringOrDefault(string value)
        {
            if (value.Equals("daily"))
                return GranularityEnum.Daily;

            if (value.Equals("weekly"))
                return GranularityEnum.Weekly;

            if (value.Equals("monthly"))
                return GranularityEnum.Monthly;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="GranularityEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string GranularityEnumToJsonValue(GranularityEnum value)
        {
            if (value == GranularityEnum.Daily)
                return "daily";

            if (value == GranularityEnum.Weekly)
                return "weekly";

            if (value == GranularityEnum.Monthly)
                return "monthly";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Granularity
        /// </summary>
        [JsonPropertyName("granularity")]
        public GranularityEnum Granularity { get; set; }

        /// <summary>
        /// Gets or Sets Series
        /// </summary>
        [JsonPropertyName("series")]
        public List<V2MarketIndexComparisonSeries> Series { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [JsonPropertyName("count")]
        public int Count { get; set; }

        /// <summary>
        /// Used to track the state of From
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> FromOption { get; private set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [JsonPropertyName("from")]
        public DateTime? From { get { return this.FromOption.Value; } set { this.FromOption = new(value); } }

        /// <summary>
        /// Used to track the state of To
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ToOption { get; private set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [JsonPropertyName("to")]
        public DateTime? To { get { return this.ToOption.Value; } set { this.ToOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2MarketIndexComparison {\n");
            sb.Append("  Game: ").Append(Game).Append("\n");
            sb.Append("  Marketplace: ").Append(Marketplace).Append("\n");
            sb.Append("  SegmentDimension: ").Append(SegmentDimension).Append("\n");
            sb.Append("  MethodologyVersion: ").Append(MethodologyVersion).Append("\n");
            sb.Append("  Granularity: ").Append(Granularity).Append("\n");
            sb.Append("  Series: ").Append(Series).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Count (int) maximum
            if (this.Count > (int)8)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value less than or equal to 8.", new [] { "Count" });
            }

            // Count (int) minimum
            if (this.Count < (int)2)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value greater than or equal to 2.", new [] { "Count" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2MarketIndexComparison" />
    /// </summary>
    public partial class V2MarketIndexComparisonJsonConverter : JsonConverter<V2MarketIndexComparison>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2MarketIndexComparisonJsonConverter" /> class.
        /// </summary>
        public V2MarketIndexComparisonJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize From
        /// </summary>
        public string FromFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize To
        /// </summary>
        public string ToFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2MarketIndexComparison" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2MarketIndexComparison Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2MarketIndexComparison.GameEnum?> game = default;
            Option<V2MarketIndexComparison.MarketplaceEnum?> marketplace = default;
            Option<V2MarketIndexComparison.SegmentDimensionEnum?> segmentDimension = default;
            Option<V2MarketIndexComparison.MethodologyVersionEnum?> methodologyVersion = default;
            Option<V2MarketIndexComparison.GranularityEnum?> granularity = default;
            Option<List<V2MarketIndexComparisonSeries>?> series = default;
            Option<int?> count = default;
            Option<DateTime?> from = default;
            Option<DateTime?> to = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "game":
                            string? gameRawValue = utf8JsonReader.GetString();
                            if (gameRawValue != null)
                            {
                                V2MarketIndexComparison.GameEnum? gameValue = V2MarketIndexComparison.GameEnumFromStringOrDefault(gameRawValue);
                                if (gameValue == null)
                                    throw new JsonException();
                                game = new Option<V2MarketIndexComparison.GameEnum?>(gameValue);
                            }
                            break;
                        case "marketplace":
                            string? marketplaceRawValue = utf8JsonReader.GetString();
                            if (marketplaceRawValue != null)
                            {
                                V2MarketIndexComparison.MarketplaceEnum? marketplaceValue = V2MarketIndexComparison.MarketplaceEnumFromStringOrDefault(marketplaceRawValue);
                                if (marketplaceValue == null)
                                    throw new JsonException();
                                marketplace = new Option<V2MarketIndexComparison.MarketplaceEnum?>(marketplaceValue);
                            }
                            break;
                        case "segment_dimension":
                            string? segmentDimensionRawValue = utf8JsonReader.GetString();
                            if (segmentDimensionRawValue != null)
                            {
                                V2MarketIndexComparison.SegmentDimensionEnum? segmentDimensionValue = V2MarketIndexComparison.SegmentDimensionEnumFromStringOrDefault(segmentDimensionRawValue);
                                if (segmentDimensionValue == null)
                                    throw new JsonException();
                                segmentDimension = new Option<V2MarketIndexComparison.SegmentDimensionEnum?>(segmentDimensionValue);
                            }
                            break;
                        case "methodology_version":
                            string? methodologyVersionRawValue = utf8JsonReader.GetString();
                            if (methodologyVersionRawValue != null)
                            {
                                V2MarketIndexComparison.MethodologyVersionEnum? methodologyVersionValue = V2MarketIndexComparison.MethodologyVersionEnumFromStringOrDefault(methodologyVersionRawValue);
                                if (methodologyVersionValue == null)
                                    throw new JsonException();
                                methodologyVersion = new Option<V2MarketIndexComparison.MethodologyVersionEnum?>(methodologyVersionValue);
                            }
                            break;
                        case "granularity":
                            string? granularityRawValue = utf8JsonReader.GetString();
                            if (granularityRawValue != null)
                            {
                                V2MarketIndexComparison.GranularityEnum? granularityValue = V2MarketIndexComparison.GranularityEnumFromStringOrDefault(granularityRawValue);
                                if (granularityValue == null)
                                    throw new JsonException();
                                granularity = new Option<V2MarketIndexComparison.GranularityEnum?>(granularityValue);
                            }
                            break;
                        case "series":
                            series = new Option<List<V2MarketIndexComparisonSeries>?>(JsonSerializer.Deserialize<List<V2MarketIndexComparisonSeries>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "from":
                            from = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "to":
                            to = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!game.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(game));

            if (!marketplace.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(marketplace));

            if (!segmentDimension.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(segmentDimension));

            if (!methodologyVersion.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(methodologyVersion));

            if (!granularity.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(granularity));

            if (!series.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(series));

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexComparison.", nameof(count));

            if (game.IsSet && game.Value == null)
                throw new ArgumentNullException(nameof(game), "Property is not nullable for class V2MarketIndexComparison.");

            if (marketplace.IsSet && marketplace.Value == null)
                throw new ArgumentNullException(nameof(marketplace), "Property is not nullable for class V2MarketIndexComparison.");

            if (segmentDimension.IsSet && segmentDimension.Value == null)
                throw new ArgumentNullException(nameof(segmentDimension), "Property is not nullable for class V2MarketIndexComparison.");

            if (methodologyVersion.IsSet && methodologyVersion.Value == null)
                throw new ArgumentNullException(nameof(methodologyVersion), "Property is not nullable for class V2MarketIndexComparison.");

            if (granularity.IsSet && granularity.Value == null)
                throw new ArgumentNullException(nameof(granularity), "Property is not nullable for class V2MarketIndexComparison.");

            if (series.IsSet && series.Value == null)
                throw new ArgumentNullException(nameof(series), "Property is not nullable for class V2MarketIndexComparison.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class V2MarketIndexComparison.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class V2MarketIndexComparison.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class V2MarketIndexComparison.");

            return new V2MarketIndexComparison(game.Value!.Value!, marketplace.Value!.Value!, segmentDimension.Value!.Value!, methodologyVersion.Value!.Value!, granularity.Value!.Value!, series.Value!, count.Value!.Value!, from, to);
        }

        /// <summary>
        /// Serializes a <see cref="V2MarketIndexComparison" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2MarketIndexComparison"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2MarketIndexComparison v2MarketIndexComparison, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2MarketIndexComparison, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2MarketIndexComparison" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2MarketIndexComparison"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2MarketIndexComparison v2MarketIndexComparison, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2MarketIndexComparison.Series == null)
                throw new ArgumentNullException(nameof(v2MarketIndexComparison.Series), "Property is required for class V2MarketIndexComparison.");

            var gameRawValue = V2MarketIndexComparison.GameEnumToJsonValue(v2MarketIndexComparison.Game);
            writer.WriteString("game", gameRawValue);
            var marketplaceRawValue = V2MarketIndexComparison.MarketplaceEnumToJsonValue(v2MarketIndexComparison.Marketplace);
            writer.WriteString("marketplace", marketplaceRawValue);
            var segmentDimensionRawValue = V2MarketIndexComparison.SegmentDimensionEnumToJsonValue(v2MarketIndexComparison.SegmentDimension);
            writer.WriteString("segment_dimension", segmentDimensionRawValue);
            var methodologyVersionRawValue = V2MarketIndexComparison.MethodologyVersionEnumToJsonValue(v2MarketIndexComparison.MethodologyVersion);
            writer.WriteString("methodology_version", methodologyVersionRawValue);
            var granularityRawValue = V2MarketIndexComparison.GranularityEnumToJsonValue(v2MarketIndexComparison.Granularity);
            writer.WriteString("granularity", granularityRawValue);
            writer.WritePropertyName("series");
            JsonSerializer.Serialize(writer, v2MarketIndexComparison.Series, jsonSerializerOptions);
            writer.WriteNumber("count", v2MarketIndexComparison.Count);

            if (v2MarketIndexComparison.FromOption.IsSet)
                writer.WriteString("from", v2MarketIndexComparison.FromOption.Value!.Value.ToString(FromFormat));

            if (v2MarketIndexComparison.ToOption.IsSet)
                writer.WriteString("to", v2MarketIndexComparison.ToOption.Value!.Value.ToString(ToFormat));
        }
    }
}
