// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2MarketIndexFreshness
    /// </summary>
    public partial class V2MarketIndexFreshness : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2MarketIndexFreshness" /> class.
        /// </summary>
        /// <param name="state">state</param>
        /// <param name="ageSeconds">ageSeconds</param>
        /// <param name="thresholdSeconds">thresholdSeconds</param>
        /// <param name="materializedAt">materializedAt</param>
        /// <param name="refreshDueAt">refreshDueAt</param>
        [JsonConstructor]
        public V2MarketIndexFreshness(StateEnum state, long ageSeconds, ThresholdSecondsEnum thresholdSeconds, DateTime materializedAt, DateTime refreshDueAt)
        {
            State = state;
            AgeSeconds = ageSeconds;
            ThresholdSeconds = thresholdSeconds;
            MaterializedAt = materializedAt;
            RefreshDueAt = refreshDueAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines State
        /// </summary>
        public enum StateEnum
        {
            /// <summary>
            /// Enum Fresh for value: fresh
            /// </summary>
            Fresh = 1,

            /// <summary>
            /// Enum Stale for value: stale
            /// </summary>
            Stale = 2
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StateEnum StateEnumFromString(string value)
        {
            if (value.Equals("fresh"))
                return StateEnum.Fresh;

            if (value.Equals("stale"))
                return StateEnum.Stale;

            throw new NotImplementedException($"Could not convert value to type StateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StateEnum? StateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("fresh"))
                return StateEnum.Fresh;

            if (value.Equals("stale"))
                return StateEnum.Stale;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StateEnumToJsonValue(StateEnum value)
        {
            if (value == StateEnum.Fresh)
                return "fresh";

            if (value == StateEnum.Stale)
                return "stale";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public StateEnum State { get; set; }

        /// <summary>
        /// Defines ThresholdSeconds
        /// </summary>
        public enum ThresholdSecondsEnum : long
        {
            /// <summary>
            /// Enum NUMBER_129600 for value: 129600
            /// </summary>
            NUMBER_129600 = 129600
        }

        /// <summary>
        /// Returns a <see cref="ThresholdSecondsEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ThresholdSecondsEnum ThresholdSecondsEnumFromString(string value)
        {
            if (value.Equals((129600).ToString(System.Globalization.CultureInfo.InvariantCulture)))
                return ThresholdSecondsEnum.NUMBER_129600;

            throw new NotImplementedException($"Could not convert value to type ThresholdSecondsEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ThresholdSecondsEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ThresholdSecondsEnum? ThresholdSecondsEnumFromStringOrDefault(string value)
        {
            if (value.Equals((129600).ToString(System.Globalization.CultureInfo.InvariantCulture)))
                return ThresholdSecondsEnum.NUMBER_129600;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ThresholdSecondsEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static long ThresholdSecondsEnumToJsonValue(ThresholdSecondsEnum value)
        {
            return (long) value;
        }

        /// <summary>
        /// Gets or Sets ThresholdSeconds
        /// </summary>
        [JsonPropertyName("threshold_seconds")]
        public ThresholdSecondsEnum ThresholdSeconds { get; set; }

        /// <summary>
        /// Gets or Sets AgeSeconds
        /// </summary>
        [JsonPropertyName("age_seconds")]
        public long AgeSeconds { get; set; }

        /// <summary>
        /// Gets or Sets MaterializedAt
        /// </summary>
        [JsonPropertyName("materialized_at")]
        public DateTime MaterializedAt { get; set; }

        /// <summary>
        /// Gets or Sets RefreshDueAt
        /// </summary>
        [JsonPropertyName("refresh_due_at")]
        public DateTime RefreshDueAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2MarketIndexFreshness {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  AgeSeconds: ").Append(AgeSeconds).Append("\n");
            sb.Append("  ThresholdSeconds: ").Append(ThresholdSeconds).Append("\n");
            sb.Append("  MaterializedAt: ").Append(MaterializedAt).Append("\n");
            sb.Append("  RefreshDueAt: ").Append(RefreshDueAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AgeSeconds (long) minimum
            if (this.AgeSeconds < (long)0)
            {
                yield return new ValidationResult("Invalid value for AgeSeconds, must be a value greater than or equal to 0.", new [] { "AgeSeconds" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2MarketIndexFreshness" />
    /// </summary>
    public partial class V2MarketIndexFreshnessJsonConverter : JsonConverter<V2MarketIndexFreshness>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2MarketIndexFreshnessJsonConverter" /> class.
        /// </summary>
        public V2MarketIndexFreshnessJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize MaterializedAt
        /// </summary>
        public string MaterializedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize RefreshDueAt
        /// </summary>
        public string RefreshDueAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2MarketIndexFreshness" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2MarketIndexFreshness Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2MarketIndexFreshness.StateEnum?> state = default;
            Option<long?> ageSeconds = default;
            Option<V2MarketIndexFreshness.ThresholdSecondsEnum?> thresholdSeconds = default;
            Option<DateTime?> materializedAt = default;
            Option<DateTime?> refreshDueAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                            {
                                V2MarketIndexFreshness.StateEnum? stateValue = V2MarketIndexFreshness.StateEnumFromStringOrDefault(stateRawValue);
                                if (stateValue == null)
                                    throw new JsonException();
                                state = new Option<V2MarketIndexFreshness.StateEnum?>(stateValue);
                            }
                            break;
                        case "age_seconds":
                            ageSeconds = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "threshold_seconds":
                            if (utf8JsonReader.TokenType == JsonTokenType.Null)
                                thresholdSeconds = new Option<V2MarketIndexFreshness.ThresholdSecondsEnum?>(null);
                            else
                            {
                                string thresholdSecondsRawValue = utf8JsonReader.GetInt64().ToString(System.Globalization.CultureInfo.InvariantCulture);
                                V2MarketIndexFreshness.ThresholdSecondsEnum? thresholdSecondsValue = V2MarketIndexFreshness.ThresholdSecondsEnumFromStringOrDefault(thresholdSecondsRawValue);
                                if (thresholdSecondsValue == null)
                                    throw new JsonException();
                                thresholdSeconds = new Option<V2MarketIndexFreshness.ThresholdSecondsEnum?>(thresholdSecondsValue);
                            }
                            break;
                        case "materialized_at":
                            materializedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "refresh_due_at":
                            refreshDueAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexFreshness.", nameof(state));

            if (!ageSeconds.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexFreshness.", nameof(ageSeconds));

            if (!thresholdSeconds.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexFreshness.", nameof(thresholdSeconds));

            if (!materializedAt.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexFreshness.", nameof(materializedAt));

            if (!refreshDueAt.IsSet)
                throw new ArgumentException("Property is required for class V2MarketIndexFreshness.", nameof(refreshDueAt));

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class V2MarketIndexFreshness.");

            if (ageSeconds.IsSet && ageSeconds.Value == null)
                throw new ArgumentNullException(nameof(ageSeconds), "Property is not nullable for class V2MarketIndexFreshness.");

            if (thresholdSeconds.IsSet && thresholdSeconds.Value == null)
                throw new ArgumentNullException(nameof(thresholdSeconds), "Property is not nullable for class V2MarketIndexFreshness.");

            if (materializedAt.IsSet && materializedAt.Value == null)
                throw new ArgumentNullException(nameof(materializedAt), "Property is not nullable for class V2MarketIndexFreshness.");

            if (refreshDueAt.IsSet && refreshDueAt.Value == null)
                throw new ArgumentNullException(nameof(refreshDueAt), "Property is not nullable for class V2MarketIndexFreshness.");

            return new V2MarketIndexFreshness(state.Value!.Value!, ageSeconds.Value!.Value!, thresholdSeconds.Value!.Value!, materializedAt.Value!.Value!, refreshDueAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2MarketIndexFreshness" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2MarketIndexFreshness"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2MarketIndexFreshness v2MarketIndexFreshness, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2MarketIndexFreshness, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2MarketIndexFreshness" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2MarketIndexFreshness"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2MarketIndexFreshness v2MarketIndexFreshness, JsonSerializerOptions jsonSerializerOptions)
        {
            var stateRawValue = V2MarketIndexFreshness.StateEnumToJsonValue(v2MarketIndexFreshness.State);
            writer.WriteString("state", stateRawValue);
            writer.WriteNumber("age_seconds", v2MarketIndexFreshness.AgeSeconds);

            writer.WriteNumber("threshold_seconds", V2MarketIndexFreshness.ThresholdSecondsEnumToJsonValue(v2MarketIndexFreshness.ThresholdSeconds));

            writer.WriteString("materialized_at", v2MarketIndexFreshness.MaterializedAt.ToString(MaterializedAtFormat));

            writer.WriteString("refresh_due_at", v2MarketIndexFreshness.RefreshDueAt.ToString(RefreshDueAtFormat));
        }
    }
}
