// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2OperationalStatus
    /// </summary>
    public partial class V2OperationalStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2OperationalStatus" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="checkedAt">checkedAt</param>
        /// <param name="components">components</param>
        /// <param name="componentStatus">Monitor-safe component status lookup keyed by component name. This mirrors components without requiring callers to depend on array order.</param>
        [JsonConstructor]
        public V2OperationalStatus(StatusEnum status, DateTime checkedAt, List<V2OperationalStatusComponent> components, Dictionary<string, V2OperationalStatus.InnerEnum> componentStatus)
        {
            Status = status;
            CheckedAt = checkedAt;
            Components = components;
            ComponentStatus = componentStatus;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Operational for value: operational
            /// </summary>
            Operational = 1,

            /// <summary>
            /// Enum Degraded for value: degraded
            /// </summary>
            Degraded = 2,

            /// <summary>
            /// Enum Outage for value: outage
            /// </summary>
            Outage = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("operational"))
                return StatusEnum.Operational;

            if (value.Equals("degraded"))
                return StatusEnum.Degraded;

            if (value.Equals("outage"))
                return StatusEnum.Outage;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("operational"))
                return StatusEnum.Operational;

            if (value.Equals("degraded"))
                return StatusEnum.Degraded;

            if (value.Equals("outage"))
                return StatusEnum.Outage;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Operational)
                return "operational";

            if (value == StatusEnum.Degraded)
                return "degraded";

            if (value == StatusEnum.Outage)
                return "outage";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Defines Inner
        /// </summary>
        public enum InnerEnum
        {
            /// <summary>
            /// Enum Operational for value: operational
            /// </summary>
            Operational = 1,

            /// <summary>
            /// Enum Degraded for value: degraded
            /// </summary>
            Degraded = 2,

            /// <summary>
            /// Enum Unavailable for value: unavailable
            /// </summary>
            Unavailable = 3
        }

        /// <summary>
        /// Returns a <see cref="InnerEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static InnerEnum InnerEnumFromString(string value)
        {
            if (value.Equals("operational"))
                return InnerEnum.Operational;

            if (value.Equals("degraded"))
                return InnerEnum.Degraded;

            if (value.Equals("unavailable"))
                return InnerEnum.Unavailable;

            throw new NotImplementedException($"Could not convert value to type InnerEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="InnerEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static InnerEnum? InnerEnumFromStringOrDefault(string value)
        {
            if (value.Equals("operational"))
                return InnerEnum.Operational;

            if (value.Equals("degraded"))
                return InnerEnum.Degraded;

            if (value.Equals("unavailable"))
                return InnerEnum.Unavailable;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="InnerEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string InnerEnumToJsonValue(InnerEnum? value)
        {
            if (value == InnerEnum.Operational)
                return "operational";

            if (value == InnerEnum.Degraded)
                return "degraded";

            if (value == InnerEnum.Unavailable)
                return "unavailable";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets CheckedAt
        /// </summary>
        [JsonPropertyName("checked_at")]
        public DateTime CheckedAt { get; set; }

        /// <summary>
        /// Gets or Sets Components
        /// </summary>
        [JsonPropertyName("components")]
        public List<V2OperationalStatusComponent> Components { get; set; }

        /// <summary>
        /// Monitor-safe component status lookup keyed by component name. This mirrors components without requiring callers to depend on array order.
        /// </summary>
        /// <value>Monitor-safe component status lookup keyed by component name. This mirrors components without requiring callers to depend on array order.</value>
        [JsonPropertyName("component_status")]
        public Dictionary<string, V2OperationalStatus.InnerEnum> ComponentStatus { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2OperationalStatus {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CheckedAt: ").Append(CheckedAt).Append("\n");
            sb.Append("  Components: ").Append(Components).Append("\n");
            sb.Append("  ComponentStatus: ").Append(ComponentStatus).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2OperationalStatus" />
    /// </summary>
    public partial class V2OperationalStatusJsonConverter : JsonConverter<V2OperationalStatus>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2OperationalStatusJsonConverter" /> class.
        /// </summary>
        public V2OperationalStatusJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CheckedAt
        /// </summary>
        public string CheckedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2OperationalStatus" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2OperationalStatus Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2OperationalStatus.StatusEnum?> status = default;
            Option<DateTime?> checkedAt = default;
            Option<List<V2OperationalStatusComponent>?> components = default;
            Option<Dictionary<string, V2OperationalStatus.InnerEnum>?> componentStatus = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                V2OperationalStatus.StatusEnum? statusValue = V2OperationalStatus.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<V2OperationalStatus.StatusEnum?>(statusValue);
                            }
                            break;
                        case "checked_at":
                            checkedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "components":
                            components = new Option<List<V2OperationalStatusComponent>?>(JsonSerializer.Deserialize<List<V2OperationalStatusComponent>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "component_status":
                            componentStatus = new Option<Dictionary<string, V2OperationalStatus.InnerEnum>?>(JsonSerializer.Deserialize<Dictionary<string, V2OperationalStatus.InnerEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class V2OperationalStatus.", nameof(status));

            if (!checkedAt.IsSet)
                throw new ArgumentException("Property is required for class V2OperationalStatus.", nameof(checkedAt));

            if (!components.IsSet)
                throw new ArgumentException("Property is required for class V2OperationalStatus.", nameof(components));

            if (!componentStatus.IsSet)
                throw new ArgumentException("Property is required for class V2OperationalStatus.", nameof(componentStatus));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class V2OperationalStatus.");

            if (checkedAt.IsSet && checkedAt.Value == null)
                throw new ArgumentNullException(nameof(checkedAt), "Property is not nullable for class V2OperationalStatus.");

            if (components.IsSet && components.Value == null)
                throw new ArgumentNullException(nameof(components), "Property is not nullable for class V2OperationalStatus.");

            if (componentStatus.IsSet && componentStatus.Value == null)
                throw new ArgumentNullException(nameof(componentStatus), "Property is not nullable for class V2OperationalStatus.");

            return new V2OperationalStatus(status.Value!.Value!, checkedAt.Value!.Value!, components.Value!, componentStatus.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2OperationalStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2OperationalStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2OperationalStatus v2OperationalStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2OperationalStatus, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2OperationalStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2OperationalStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2OperationalStatus v2OperationalStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2OperationalStatus.Components == null)
                throw new ArgumentNullException(nameof(v2OperationalStatus.Components), "Property is required for class V2OperationalStatus.");

            if (v2OperationalStatus.ComponentStatus == null)
                throw new ArgumentNullException(nameof(v2OperationalStatus.ComponentStatus), "Property is required for class V2OperationalStatus.");

            var statusRawValue = V2OperationalStatus.StatusEnumToJsonValue(v2OperationalStatus.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("checked_at", v2OperationalStatus.CheckedAt.ToString(CheckedAtFormat));

            writer.WritePropertyName("components");
            JsonSerializer.Serialize(writer, v2OperationalStatus.Components, jsonSerializerOptions);
            writer.WritePropertyName("component_status");
            JsonSerializer.Serialize(writer, v2OperationalStatus.ComponentStatus, jsonSerializerOptions);
        }
    }
}
