// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2OperationFailure
    /// </summary>
    public partial class V2OperationFailure : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2OperationFailure" /> class.
        /// </summary>
        /// <param name="code">Stable machine-readable failure code.</param>
        /// <param name="origin">Identifies whether the failure originated in the customer instruction, customer account, Steam, or OpenSkin.</param>
        /// <param name="transient">True when retrying later may succeed without changing the instruction. Before retrying a Steam action, follow the endpoint’s idempotency and reconciliation rules.</param>
        /// <param name="observedAt">observedAt</param>
        [JsonConstructor]
        public V2OperationFailure(string code, OriginEnum origin, bool transient, Option<DateTime?> observedAt = default)
        {
            Code = code;
            Origin = origin;
            Transient = transient;
            ObservedAtOption = observedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Identifies whether the failure originated in the customer instruction, customer account, Steam, or OpenSkin.
        /// </summary>
        /// <value>Identifies whether the failure originated in the customer instruction, customer account, Steam, or OpenSkin.</value>
        public enum OriginEnum
        {
            /// <summary>
            /// Enum CustomerInstruction for value: customer_instruction
            /// </summary>
            CustomerInstruction = 1,

            /// <summary>
            /// Enum CustomerAccount for value: customer_account
            /// </summary>
            CustomerAccount = 2,

            /// <summary>
            /// Enum Steam for value: steam
            /// </summary>
            Steam = 3,

            /// <summary>
            /// Enum Openskin for value: openskin
            /// </summary>
            Openskin = 4
        }

        /// <summary>
        /// Returns a <see cref="OriginEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OriginEnum OriginEnumFromString(string value)
        {
            if (value.Equals("customer_instruction"))
                return OriginEnum.CustomerInstruction;

            if (value.Equals("customer_account"))
                return OriginEnum.CustomerAccount;

            if (value.Equals("steam"))
                return OriginEnum.Steam;

            if (value.Equals("openskin"))
                return OriginEnum.Openskin;

            throw new NotImplementedException($"Could not convert value to type OriginEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OriginEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OriginEnum? OriginEnumFromStringOrDefault(string value)
        {
            if (value.Equals("customer_instruction"))
                return OriginEnum.CustomerInstruction;

            if (value.Equals("customer_account"))
                return OriginEnum.CustomerAccount;

            if (value.Equals("steam"))
                return OriginEnum.Steam;

            if (value.Equals("openskin"))
                return OriginEnum.Openskin;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OriginEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OriginEnumToJsonValue(OriginEnum value)
        {
            if (value == OriginEnum.CustomerInstruction)
                return "customer_instruction";

            if (value == OriginEnum.CustomerAccount)
                return "customer_account";

            if (value == OriginEnum.Steam)
                return "steam";

            if (value == OriginEnum.Openskin)
                return "openskin";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Identifies whether the failure originated in the customer instruction, customer account, Steam, or OpenSkin.
        /// </summary>
        /// <value>Identifies whether the failure originated in the customer instruction, customer account, Steam, or OpenSkin.</value>
        [JsonPropertyName("origin")]
        public OriginEnum Origin { get; set; }

        /// <summary>
        /// Stable machine-readable failure code.
        /// </summary>
        /// <value>Stable machine-readable failure code.</value>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// True when retrying later may succeed without changing the instruction. Before retrying a Steam action, follow the endpoint’s idempotency and reconciliation rules.
        /// </summary>
        /// <value>True when retrying later may succeed without changing the instruction. Before retrying a Steam action, follow the endpoint’s idempotency and reconciliation rules.</value>
        [JsonPropertyName("transient")]
        public bool Transient { get; set; }

        /// <summary>
        /// Used to track the state of ObservedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ObservedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ObservedAt
        /// </summary>
        [JsonPropertyName("observed_at")]
        public DateTime? ObservedAt { get { return this.ObservedAtOption.Value; } set { this.ObservedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2OperationFailure {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Transient: ").Append(Transient).Append("\n");
            sb.Append("  ObservedAt: ").Append(ObservedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2OperationFailure" />
    /// </summary>
    public partial class V2OperationFailureJsonConverter : JsonConverter<V2OperationFailure>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2OperationFailureJsonConverter" /> class.
        /// </summary>
        public V2OperationFailureJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ObservedAt
        /// </summary>
        public string ObservedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2OperationFailure" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2OperationFailure Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<V2OperationFailure.OriginEnum?> origin = default;
            Option<bool?> transient = default;
            Option<DateTime?> observedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "origin":
                            string? originRawValue = utf8JsonReader.GetString();
                            if (originRawValue != null)
                            {
                                V2OperationFailure.OriginEnum? originValue = V2OperationFailure.OriginEnumFromStringOrDefault(originRawValue);
                                if (originValue == null)
                                    throw new JsonException();
                                origin = new Option<V2OperationFailure.OriginEnum?>(originValue);
                            }
                            break;
                        case "transient":
                            transient = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "observed_at":
                            observedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class V2OperationFailure.", nameof(code));

            if (!origin.IsSet)
                throw new ArgumentException("Property is required for class V2OperationFailure.", nameof(origin));

            if (!transient.IsSet)
                throw new ArgumentException("Property is required for class V2OperationFailure.", nameof(transient));

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class V2OperationFailure.");

            if (origin.IsSet && origin.Value == null)
                throw new ArgumentNullException(nameof(origin), "Property is not nullable for class V2OperationFailure.");

            if (transient.IsSet && transient.Value == null)
                throw new ArgumentNullException(nameof(transient), "Property is not nullable for class V2OperationFailure.");

            if (observedAt.IsSet && observedAt.Value == null)
                throw new ArgumentNullException(nameof(observedAt), "Property is not nullable for class V2OperationFailure.");

            return new V2OperationFailure(code.Value!, origin.Value!.Value!, transient.Value!.Value!, observedAt);
        }

        /// <summary>
        /// Serializes a <see cref="V2OperationFailure" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2OperationFailure"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2OperationFailure v2OperationFailure, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2OperationFailure, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2OperationFailure" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2OperationFailure"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2OperationFailure v2OperationFailure, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2OperationFailure.Code == null)
                throw new ArgumentNullException(nameof(v2OperationFailure.Code), "Property is required for class V2OperationFailure.");

            writer.WriteString("code", v2OperationFailure.Code);

            var originRawValue = V2OperationFailure.OriginEnumToJsonValue(v2OperationFailure.Origin);
            writer.WriteString("origin", originRawValue);
            writer.WriteBoolean("transient", v2OperationFailure.Transient);

            if (v2OperationFailure.ObservedAtOption.IsSet)
                writer.WriteString("observed_at", v2OperationFailure.ObservedAtOption.Value!.Value.ToString(ObservedAtFormat));
        }
    }
}
