// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2PriceFreshness
    /// </summary>
    public partial class V2PriceFreshness : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2PriceFreshness" /> class.
        /// </summary>
        /// <param name="state">state</param>
        /// <param name="ageSeconds">ageSeconds</param>
        /// <param name="thresholdSeconds">thresholdSeconds</param>
        [JsonConstructor]
        public V2PriceFreshness(StateEnum state, long ageSeconds, long thresholdSeconds)
        {
            State = state;
            AgeSeconds = ageSeconds;
            ThresholdSeconds = thresholdSeconds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines State
        /// </summary>
        public enum StateEnum
        {
            /// <summary>
            /// Enum Fresh for value: fresh
            /// </summary>
            Fresh = 1,

            /// <summary>
            /// Enum Stale for value: stale
            /// </summary>
            Stale = 2
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StateEnum StateEnumFromString(string value)
        {
            if (value.Equals("fresh"))
                return StateEnum.Fresh;

            if (value.Equals("stale"))
                return StateEnum.Stale;

            throw new NotImplementedException($"Could not convert value to type StateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StateEnum? StateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("fresh"))
                return StateEnum.Fresh;

            if (value.Equals("stale"))
                return StateEnum.Stale;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StateEnumToJsonValue(StateEnum value)
        {
            if (value == StateEnum.Fresh)
                return "fresh";

            if (value == StateEnum.Stale)
                return "stale";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public StateEnum State { get; set; }

        /// <summary>
        /// Gets or Sets AgeSeconds
        /// </summary>
        [JsonPropertyName("age_seconds")]
        public long AgeSeconds { get; set; }

        /// <summary>
        /// Gets or Sets ThresholdSeconds
        /// </summary>
        [JsonPropertyName("threshold_seconds")]
        public long ThresholdSeconds { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2PriceFreshness {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  AgeSeconds: ").Append(AgeSeconds).Append("\n");
            sb.Append("  ThresholdSeconds: ").Append(ThresholdSeconds).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AgeSeconds (long) minimum
            if (this.AgeSeconds < (long)0)
            {
                yield return new ValidationResult("Invalid value for AgeSeconds, must be a value greater than or equal to 0.", new [] { "AgeSeconds" });
            }

            // ThresholdSeconds (long) minimum
            if (this.ThresholdSeconds < (long)0)
            {
                yield return new ValidationResult("Invalid value for ThresholdSeconds, must be a value greater than or equal to 0.", new [] { "ThresholdSeconds" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2PriceFreshness" />
    /// </summary>
    public partial class V2PriceFreshnessJsonConverter : JsonConverter<V2PriceFreshness>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2PriceFreshnessJsonConverter" /> class.
        /// </summary>
        public V2PriceFreshnessJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2PriceFreshness" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2PriceFreshness Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2PriceFreshness.StateEnum?> state = default;
            Option<long?> ageSeconds = default;
            Option<long?> thresholdSeconds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                            {
                                V2PriceFreshness.StateEnum? stateValue = V2PriceFreshness.StateEnumFromStringOrDefault(stateRawValue);
                                if (stateValue == null)
                                    throw new JsonException();
                                state = new Option<V2PriceFreshness.StateEnum?>(stateValue);
                            }
                            break;
                        case "age_seconds":
                            ageSeconds = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "threshold_seconds":
                            thresholdSeconds = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class V2PriceFreshness.", nameof(state));

            if (!ageSeconds.IsSet)
                throw new ArgumentException("Property is required for class V2PriceFreshness.", nameof(ageSeconds));

            if (!thresholdSeconds.IsSet)
                throw new ArgumentException("Property is required for class V2PriceFreshness.", nameof(thresholdSeconds));

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class V2PriceFreshness.");

            if (ageSeconds.IsSet && ageSeconds.Value == null)
                throw new ArgumentNullException(nameof(ageSeconds), "Property is not nullable for class V2PriceFreshness.");

            if (thresholdSeconds.IsSet && thresholdSeconds.Value == null)
                throw new ArgumentNullException(nameof(thresholdSeconds), "Property is not nullable for class V2PriceFreshness.");

            return new V2PriceFreshness(state.Value!.Value!, ageSeconds.Value!.Value!, thresholdSeconds.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2PriceFreshness" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2PriceFreshness"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2PriceFreshness v2PriceFreshness, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2PriceFreshness, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2PriceFreshness" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2PriceFreshness"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2PriceFreshness v2PriceFreshness, JsonSerializerOptions jsonSerializerOptions)
        {
            var stateRawValue = V2PriceFreshness.StateEnumToJsonValue(v2PriceFreshness.State);
            writer.WriteString("state", stateRawValue);
            writer.WriteNumber("age_seconds", v2PriceFreshness.AgeSeconds);

            writer.WriteNumber("threshold_seconds", v2PriceFreshness.ThresholdSeconds);
        }
    }
}
