// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2RenderItemRequestItem
    /// </summary>
    public partial class V2RenderItemRequestItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2RenderItemRequestItem" /> class.
        /// </summary>
        /// <param name="family">family</param>
        /// <param name="definitionIndex">definitionIndex</param>
        /// <param name="paintIndex">Required only for weapon, knife, and gloves</param>
        [JsonConstructor]
        public V2RenderItemRequestItem(FamilyEnum family, int definitionIndex, Option<int?> paintIndex = default)
        {
            Family = family;
            DefinitionIndex = definitionIndex;
            PaintIndexOption = paintIndex;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Family
        /// </summary>
        public enum FamilyEnum
        {
            /// <summary>
            /// Enum Weapon for value: weapon
            /// </summary>
            Weapon = 1,

            /// <summary>
            /// Enum Knife for value: knife
            /// </summary>
            Knife = 2,

            /// <summary>
            /// Enum Gloves for value: gloves
            /// </summary>
            Gloves = 3,

            /// <summary>
            /// Enum Sticker for value: sticker
            /// </summary>
            Sticker = 4,

            /// <summary>
            /// Enum StickerSlab for value: sticker-slab
            /// </summary>
            StickerSlab = 5,

            /// <summary>
            /// Enum Charm for value: charm
            /// </summary>
            Charm = 6,

            /// <summary>
            /// Enum Agent for value: agent
            /// </summary>
            Agent = 7,

            /// <summary>
            /// Enum Patch for value: patch
            /// </summary>
            Patch = 8,

            /// <summary>
            /// Enum MusicKit for value: music-kit
            /// </summary>
            MusicKit = 9
        }

        /// <summary>
        /// Returns a <see cref="FamilyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FamilyEnum FamilyEnumFromString(string value)
        {
            if (value.Equals("weapon"))
                return FamilyEnum.Weapon;

            if (value.Equals("knife"))
                return FamilyEnum.Knife;

            if (value.Equals("gloves"))
                return FamilyEnum.Gloves;

            if (value.Equals("sticker"))
                return FamilyEnum.Sticker;

            if (value.Equals("sticker-slab"))
                return FamilyEnum.StickerSlab;

            if (value.Equals("charm"))
                return FamilyEnum.Charm;

            if (value.Equals("agent"))
                return FamilyEnum.Agent;

            if (value.Equals("patch"))
                return FamilyEnum.Patch;

            if (value.Equals("music-kit"))
                return FamilyEnum.MusicKit;

            throw new NotImplementedException($"Could not convert value to type FamilyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FamilyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FamilyEnum? FamilyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("weapon"))
                return FamilyEnum.Weapon;

            if (value.Equals("knife"))
                return FamilyEnum.Knife;

            if (value.Equals("gloves"))
                return FamilyEnum.Gloves;

            if (value.Equals("sticker"))
                return FamilyEnum.Sticker;

            if (value.Equals("sticker-slab"))
                return FamilyEnum.StickerSlab;

            if (value.Equals("charm"))
                return FamilyEnum.Charm;

            if (value.Equals("agent"))
                return FamilyEnum.Agent;

            if (value.Equals("patch"))
                return FamilyEnum.Patch;

            if (value.Equals("music-kit"))
                return FamilyEnum.MusicKit;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FamilyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FamilyEnumToJsonValue(FamilyEnum value)
        {
            if (value == FamilyEnum.Weapon)
                return "weapon";

            if (value == FamilyEnum.Knife)
                return "knife";

            if (value == FamilyEnum.Gloves)
                return "gloves";

            if (value == FamilyEnum.Sticker)
                return "sticker";

            if (value == FamilyEnum.StickerSlab)
                return "sticker-slab";

            if (value == FamilyEnum.Charm)
                return "charm";

            if (value == FamilyEnum.Agent)
                return "agent";

            if (value == FamilyEnum.Patch)
                return "patch";

            if (value == FamilyEnum.MusicKit)
                return "music-kit";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Family
        /// </summary>
        [JsonPropertyName("family")]
        public FamilyEnum Family { get; set; }

        /// <summary>
        /// Gets or Sets DefinitionIndex
        /// </summary>
        [JsonPropertyName("definition_index")]
        public int DefinitionIndex { get; set; }

        /// <summary>
        /// Used to track the state of PaintIndex
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PaintIndexOption { get; private set; }

        /// <summary>
        /// Required only for weapon, knife, and gloves
        /// </summary>
        /// <value>Required only for weapon, knife, and gloves</value>
        [JsonPropertyName("paint_index")]
        public int? PaintIndex { get { return this.PaintIndexOption.Value; } set { this.PaintIndexOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2RenderItemRequestItem {\n");
            sb.Append("  Family: ").Append(Family).Append("\n");
            sb.Append("  DefinitionIndex: ").Append(DefinitionIndex).Append("\n");
            sb.Append("  PaintIndex: ").Append(PaintIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DefinitionIndex (int) minimum
            if (this.DefinitionIndex < (int)1)
            {
                yield return new ValidationResult("Invalid value for DefinitionIndex, must be a value greater than or equal to 1.", new [] { "DefinitionIndex" });
            }

            // PaintIndex (int) minimum
            if (this.PaintIndexOption.IsSet && this.PaintIndexOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for PaintIndex, must be a value greater than or equal to 0.", new [] { "PaintIndex" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2RenderItemRequestItem" />
    /// </summary>
    public partial class V2RenderItemRequestItemJsonConverter : JsonConverter<V2RenderItemRequestItem>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2RenderItemRequestItemJsonConverter" /> class.
        /// </summary>
        public V2RenderItemRequestItemJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2RenderItemRequestItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2RenderItemRequestItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2RenderItemRequestItem.FamilyEnum?> family = default;
            Option<int?> definitionIndex = default;
            Option<int?> paintIndex = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "family":
                            string? familyRawValue = utf8JsonReader.GetString();
                            if (familyRawValue != null)
                            {
                                V2RenderItemRequestItem.FamilyEnum? familyValue = V2RenderItemRequestItem.FamilyEnumFromStringOrDefault(familyRawValue);
                                if (familyValue == null)
                                    throw new JsonException();
                                family = new Option<V2RenderItemRequestItem.FamilyEnum?>(familyValue);
                            }
                            break;
                        case "definition_index":
                            definitionIndex = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "paint_index":
                            paintIndex = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!family.IsSet)
                throw new ArgumentException("Property is required for class V2RenderItemRequestItem.", nameof(family));

            if (!definitionIndex.IsSet)
                throw new ArgumentException("Property is required for class V2RenderItemRequestItem.", nameof(definitionIndex));

            if (family.IsSet && family.Value == null)
                throw new ArgumentNullException(nameof(family), "Property is not nullable for class V2RenderItemRequestItem.");

            if (definitionIndex.IsSet && definitionIndex.Value == null)
                throw new ArgumentNullException(nameof(definitionIndex), "Property is not nullable for class V2RenderItemRequestItem.");

            if (paintIndex.IsSet && paintIndex.Value == null)
                throw new ArgumentNullException(nameof(paintIndex), "Property is not nullable for class V2RenderItemRequestItem.");

            return new V2RenderItemRequestItem(family.Value!.Value!, definitionIndex.Value!.Value!, paintIndex);
        }

        /// <summary>
        /// Serializes a <see cref="V2RenderItemRequestItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2RenderItemRequestItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2RenderItemRequestItem v2RenderItemRequestItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2RenderItemRequestItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2RenderItemRequestItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2RenderItemRequestItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2RenderItemRequestItem v2RenderItemRequestItem, JsonSerializerOptions jsonSerializerOptions)
        {
            var familyRawValue = V2RenderItemRequestItem.FamilyEnumToJsonValue(v2RenderItemRequestItem.Family);
            writer.WriteString("family", familyRawValue);
            writer.WriteNumber("definition_index", v2RenderItemRequestItem.DefinitionIndex);

            if (v2RenderItemRequestItem.PaintIndexOption.IsSet)
                writer.WriteNumber("paint_index", v2RenderItemRequestItem.PaintIndexOption.Value!.Value);
        }
    }
}
