// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2SteamTradeHistorySyncRequest
    /// </summary>
    public partial class V2SteamTradeHistorySyncRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2SteamTradeHistorySyncRequest" /> class.
        /// </summary>
        /// <param name="cursor">Opaque account-bound cursor returned by the previous history-sync command. Omit for the first page.</param>
        [JsonConstructor]
        public V2SteamTradeHistorySyncRequest(Option<string?> cursor = default)
        {
            CursorOption = cursor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Cursor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CursorOption { get; private set; }

        /// <summary>
        /// Opaque account-bound cursor returned by the previous history-sync command. Omit for the first page.
        /// </summary>
        /// <value>Opaque account-bound cursor returned by the previous history-sync command. Omit for the first page.</value>
        [JsonPropertyName("cursor")]
        public string? Cursor { get { return this.CursorOption.Value; } set { this.CursorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2SteamTradeHistorySyncRequest {\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2SteamTradeHistorySyncRequest" />
    /// </summary>
    public partial class V2SteamTradeHistorySyncRequestJsonConverter : JsonConverter<V2SteamTradeHistorySyncRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2SteamTradeHistorySyncRequestJsonConverter" /> class.
        /// </summary>
        public V2SteamTradeHistorySyncRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2SteamTradeHistorySyncRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2SteamTradeHistorySyncRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> cursor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "cursor":
                            cursor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (cursor.IsSet && cursor.Value == null)
                throw new ArgumentNullException(nameof(cursor), "Property is not nullable for class V2SteamTradeHistorySyncRequest.");

            return new V2SteamTradeHistorySyncRequest(cursor);
        }

        /// <summary>
        /// Serializes a <see cref="V2SteamTradeHistorySyncRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2SteamTradeHistorySyncRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2SteamTradeHistorySyncRequest v2SteamTradeHistorySyncRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2SteamTradeHistorySyncRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2SteamTradeHistorySyncRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2SteamTradeHistorySyncRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2SteamTradeHistorySyncRequest v2SteamTradeHistorySyncRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2SteamTradeHistorySyncRequest.CursorOption.IsSet && v2SteamTradeHistorySyncRequest.Cursor == null)
                throw new ArgumentNullException(nameof(v2SteamTradeHistorySyncRequest.Cursor), "Property is required for class V2SteamTradeHistorySyncRequest.");

            if (v2SteamTradeHistorySyncRequest.CursorOption.IsSet)
                writer.WriteString("cursor", v2SteamTradeHistorySyncRequest.Cursor);
        }
    }
}
