// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2SteamAccountHealthSession
    /// </summary>
    public partial class V2SteamAccountHealthSession : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2SteamAccountHealthSession" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="refreshTokenAvailable">refreshTokenAvailable</param>
        /// <param name="expiresAt">expiresAt</param>
        /// <param name="lastConnectedAt">lastConnectedAt</param>
        [JsonConstructor]
        public V2SteamAccountHealthSession(StatusEnum status, bool refreshTokenAvailable, Option<DateTime?> expiresAt = default, Option<DateTime?> lastConnectedAt = default)
        {
            Status = status;
            RefreshTokenAvailable = refreshTokenAvailable;
            ExpiresAtOption = expiresAt;
            LastConnectedAtOption = lastConnectedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Fresh for value: fresh
            /// </summary>
            Fresh = 1,

            /// <summary>
            /// Enum Expiring for value: expiring
            /// </summary>
            Expiring = 2,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            Active = 3,

            /// <summary>
            /// Enum Expired for value: expired
            /// </summary>
            Expired = 4,

            /// <summary>
            /// Enum Refreshable for value: refreshable
            /// </summary>
            Refreshable = 5,

            /// <summary>
            /// Enum Unavailable for value: unavailable
            /// </summary>
            Unavailable = 6
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("fresh"))
                return StatusEnum.Fresh;

            if (value.Equals("expiring"))
                return StatusEnum.Expiring;

            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("expired"))
                return StatusEnum.Expired;

            if (value.Equals("refreshable"))
                return StatusEnum.Refreshable;

            if (value.Equals("unavailable"))
                return StatusEnum.Unavailable;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("fresh"))
                return StatusEnum.Fresh;

            if (value.Equals("expiring"))
                return StatusEnum.Expiring;

            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("expired"))
                return StatusEnum.Expired;

            if (value.Equals("refreshable"))
                return StatusEnum.Refreshable;

            if (value.Equals("unavailable"))
                return StatusEnum.Unavailable;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Fresh)
                return "fresh";

            if (value == StatusEnum.Expiring)
                return "expiring";

            if (value == StatusEnum.Active)
                return "active";

            if (value == StatusEnum.Expired)
                return "expired";

            if (value == StatusEnum.Refreshable)
                return "refreshable";

            if (value == StatusEnum.Unavailable)
                return "unavailable";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets RefreshTokenAvailable
        /// </summary>
        [JsonPropertyName("refresh_token_available")]
        public bool RefreshTokenAvailable { get; set; }

        /// <summary>
        /// Used to track the state of ExpiresAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ExpiresAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expires_at")]
        public DateTime? ExpiresAt { get { return this.ExpiresAtOption.Value; } set { this.ExpiresAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastConnectedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastConnectedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastConnectedAt
        /// </summary>
        [JsonPropertyName("last_connected_at")]
        public DateTime? LastConnectedAt { get { return this.LastConnectedAtOption.Value; } set { this.LastConnectedAtOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2SteamAccountHealthSession {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RefreshTokenAvailable: ").Append(RefreshTokenAvailable).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  LastConnectedAt: ").Append(LastConnectedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2SteamAccountHealthSession" />
    /// </summary>
    public partial class V2SteamAccountHealthSessionJsonConverter : JsonConverter<V2SteamAccountHealthSession>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2SteamAccountHealthSessionJsonConverter" /> class.
        /// </summary>
        public V2SteamAccountHealthSessionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastConnectedAt
        /// </summary>
        public string LastConnectedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2SteamAccountHealthSession" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2SteamAccountHealthSession Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2SteamAccountHealthSession.StatusEnum?> status = default;
            Option<bool?> refreshTokenAvailable = default;
            Option<DateTime?> expiresAt = default;
            Option<DateTime?> lastConnectedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                V2SteamAccountHealthSession.StatusEnum? statusValue = V2SteamAccountHealthSession.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<V2SteamAccountHealthSession.StatusEnum?>(statusValue);
                            }
                            break;
                        case "refresh_token_available":
                            refreshTokenAvailable = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "last_connected_at":
                            lastConnectedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class V2SteamAccountHealthSession.", nameof(status));

            if (!refreshTokenAvailable.IsSet)
                throw new ArgumentException("Property is required for class V2SteamAccountHealthSession.", nameof(refreshTokenAvailable));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class V2SteamAccountHealthSession.");

            if (refreshTokenAvailable.IsSet && refreshTokenAvailable.Value == null)
                throw new ArgumentNullException(nameof(refreshTokenAvailable), "Property is not nullable for class V2SteamAccountHealthSession.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class V2SteamAccountHealthSession.");

            if (lastConnectedAt.IsSet && lastConnectedAt.Value == null)
                throw new ArgumentNullException(nameof(lastConnectedAt), "Property is not nullable for class V2SteamAccountHealthSession.");

            return new V2SteamAccountHealthSession(status.Value!.Value!, refreshTokenAvailable.Value!.Value!, expiresAt, lastConnectedAt);
        }

        /// <summary>
        /// Serializes a <see cref="V2SteamAccountHealthSession" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2SteamAccountHealthSession"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2SteamAccountHealthSession v2SteamAccountHealthSession, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2SteamAccountHealthSession, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2SteamAccountHealthSession" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2SteamAccountHealthSession"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2SteamAccountHealthSession v2SteamAccountHealthSession, JsonSerializerOptions jsonSerializerOptions)
        {
            var statusRawValue = V2SteamAccountHealthSession.StatusEnumToJsonValue(v2SteamAccountHealthSession.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteBoolean("refresh_token_available", v2SteamAccountHealthSession.RefreshTokenAvailable);

            if (v2SteamAccountHealthSession.ExpiresAtOption.IsSet)
                writer.WriteString("expires_at", v2SteamAccountHealthSession.ExpiresAtOption.Value!.Value.ToString(ExpiresAtFormat));

            if (v2SteamAccountHealthSession.LastConnectedAtOption.IsSet)
                writer.WriteString("last_connected_at", v2SteamAccountHealthSession.LastConnectedAtOption.Value!.Value.ToString(LastConnectedAtFormat));
        }
    }
}
