// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2SteamBanSignals
    /// </summary>
    public partial class V2SteamBanSignals : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2SteamBanSignals" /> class.
        /// </summary>
        /// <param name="communityBanned">communityBanned</param>
        /// <param name="vacBanned">vacBanned</param>
        /// <param name="vacBanCount">vacBanCount</param>
        /// <param name="daysSinceLastBan">daysSinceLastBan</param>
        /// <param name="gameBanCount">gameBanCount</param>
        /// <param name="economyBan">economyBan</param>
        [JsonConstructor]
        public V2SteamBanSignals(bool communityBanned, bool vacBanned, int vacBanCount, int daysSinceLastBan, int gameBanCount, string economyBan)
        {
            CommunityBanned = communityBanned;
            VacBanned = vacBanned;
            VacBanCount = vacBanCount;
            DaysSinceLastBan = daysSinceLastBan;
            GameBanCount = gameBanCount;
            EconomyBan = economyBan;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CommunityBanned
        /// </summary>
        [JsonPropertyName("community_banned")]
        public bool CommunityBanned { get; set; }

        /// <summary>
        /// Gets or Sets VacBanned
        /// </summary>
        [JsonPropertyName("vac_banned")]
        public bool VacBanned { get; set; }

        /// <summary>
        /// Gets or Sets VacBanCount
        /// </summary>
        [JsonPropertyName("vac_ban_count")]
        public int VacBanCount { get; set; }

        /// <summary>
        /// Gets or Sets DaysSinceLastBan
        /// </summary>
        [JsonPropertyName("days_since_last_ban")]
        public int DaysSinceLastBan { get; set; }

        /// <summary>
        /// Gets or Sets GameBanCount
        /// </summary>
        [JsonPropertyName("game_ban_count")]
        public int GameBanCount { get; set; }

        /// <summary>
        /// Gets or Sets EconomyBan
        /// </summary>
        [JsonPropertyName("economy_ban")]
        public string EconomyBan { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2SteamBanSignals {\n");
            sb.Append("  CommunityBanned: ").Append(CommunityBanned).Append("\n");
            sb.Append("  VacBanned: ").Append(VacBanned).Append("\n");
            sb.Append("  VacBanCount: ").Append(VacBanCount).Append("\n");
            sb.Append("  DaysSinceLastBan: ").Append(DaysSinceLastBan).Append("\n");
            sb.Append("  GameBanCount: ").Append(GameBanCount).Append("\n");
            sb.Append("  EconomyBan: ").Append(EconomyBan).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // VacBanCount (int) minimum
            if (this.VacBanCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for VacBanCount, must be a value greater than or equal to 0.", new [] { "VacBanCount" });
            }

            // DaysSinceLastBan (int) minimum
            if (this.DaysSinceLastBan < (int)0)
            {
                yield return new ValidationResult("Invalid value for DaysSinceLastBan, must be a value greater than or equal to 0.", new [] { "DaysSinceLastBan" });
            }

            // GameBanCount (int) minimum
            if (this.GameBanCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for GameBanCount, must be a value greater than or equal to 0.", new [] { "GameBanCount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2SteamBanSignals" />
    /// </summary>
    public partial class V2SteamBanSignalsJsonConverter : JsonConverter<V2SteamBanSignals>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2SteamBanSignalsJsonConverter" /> class.
        /// </summary>
        public V2SteamBanSignalsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2SteamBanSignals" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2SteamBanSignals Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> communityBanned = default;
            Option<bool?> vacBanned = default;
            Option<int?> vacBanCount = default;
            Option<int?> daysSinceLastBan = default;
            Option<int?> gameBanCount = default;
            Option<string?> economyBan = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "community_banned":
                            communityBanned = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "vac_banned":
                            vacBanned = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "vac_ban_count":
                            vacBanCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "days_since_last_ban":
                            daysSinceLastBan = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "game_ban_count":
                            gameBanCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "economy_ban":
                            economyBan = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!communityBanned.IsSet)
                throw new ArgumentException("Property is required for class V2SteamBanSignals.", nameof(communityBanned));

            if (!vacBanned.IsSet)
                throw new ArgumentException("Property is required for class V2SteamBanSignals.", nameof(vacBanned));

            if (!vacBanCount.IsSet)
                throw new ArgumentException("Property is required for class V2SteamBanSignals.", nameof(vacBanCount));

            if (!daysSinceLastBan.IsSet)
                throw new ArgumentException("Property is required for class V2SteamBanSignals.", nameof(daysSinceLastBan));

            if (!gameBanCount.IsSet)
                throw new ArgumentException("Property is required for class V2SteamBanSignals.", nameof(gameBanCount));

            if (!economyBan.IsSet)
                throw new ArgumentException("Property is required for class V2SteamBanSignals.", nameof(economyBan));

            if (communityBanned.IsSet && communityBanned.Value == null)
                throw new ArgumentNullException(nameof(communityBanned), "Property is not nullable for class V2SteamBanSignals.");

            if (vacBanned.IsSet && vacBanned.Value == null)
                throw new ArgumentNullException(nameof(vacBanned), "Property is not nullable for class V2SteamBanSignals.");

            if (vacBanCount.IsSet && vacBanCount.Value == null)
                throw new ArgumentNullException(nameof(vacBanCount), "Property is not nullable for class V2SteamBanSignals.");

            if (daysSinceLastBan.IsSet && daysSinceLastBan.Value == null)
                throw new ArgumentNullException(nameof(daysSinceLastBan), "Property is not nullable for class V2SteamBanSignals.");

            if (gameBanCount.IsSet && gameBanCount.Value == null)
                throw new ArgumentNullException(nameof(gameBanCount), "Property is not nullable for class V2SteamBanSignals.");

            if (economyBan.IsSet && economyBan.Value == null)
                throw new ArgumentNullException(nameof(economyBan), "Property is not nullable for class V2SteamBanSignals.");

            return new V2SteamBanSignals(communityBanned.Value!.Value!, vacBanned.Value!.Value!, vacBanCount.Value!.Value!, daysSinceLastBan.Value!.Value!, gameBanCount.Value!.Value!, economyBan.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2SteamBanSignals" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2SteamBanSignals"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2SteamBanSignals v2SteamBanSignals, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2SteamBanSignals, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2SteamBanSignals" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2SteamBanSignals"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2SteamBanSignals v2SteamBanSignals, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2SteamBanSignals.EconomyBan == null)
                throw new ArgumentNullException(nameof(v2SteamBanSignals.EconomyBan), "Property is required for class V2SteamBanSignals.");

            writer.WriteBoolean("community_banned", v2SteamBanSignals.CommunityBanned);

            writer.WriteBoolean("vac_banned", v2SteamBanSignals.VacBanned);

            writer.WriteNumber("vac_ban_count", v2SteamBanSignals.VacBanCount);

            writer.WriteNumber("days_since_last_ban", v2SteamBanSignals.DaysSinceLastBan);

            writer.WriteNumber("game_ban_count", v2SteamBanSignals.GameBanCount);

            writer.WriteString("economy_ban", v2SteamBanSignals.EconomyBan);
        }
    }
}
