// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// Record of the trade policy and rolling budget checks applied before execution. It does not indicate whether the trade was financially desirable.
    /// </summary>
    public partial class V2TradeAuthorizationReceipt : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2TradeAuthorizationReceipt" /> class.
        /// </summary>
        /// <param name="schemaVersion">schemaVersion</param>
        /// <param name="policyRevision">policyRevision</param>
        /// <param name="allowOutboundGifts">allowOutboundGifts</param>
        /// <param name="requirePartnerAllowlist">requirePartnerAllowlist</param>
        /// <param name="partnerAllowlisted">Whether the exact trade partner was present in the policy allowlist when OpenSkin authorized execution.</param>
        /// <param name="maxOfferedAssets">maxOfferedAssets</param>
        /// <param name="maxRequestedAssets">maxRequestedAssets</param>
        /// <param name="maxOfferedValueUsd">maxOfferedValueUsd</param>
        /// <param name="maxRolling24hTradeCount">maxRolling24hTradeCount</param>
        /// <param name="maxRolling24hOfferedValueUsd">maxRolling24hOfferedValueUsd</param>
        /// <param name="rollingTradeCountBefore">rollingTradeCountBefore</param>
        /// <param name="rollingOfferedValueUsdBefore">rollingOfferedValueUsdBefore</param>
        /// <param name="rollingTradeCountAfter">rollingTradeCountAfter</param>
        /// <param name="rollingOfferedValueUsdAfter">rollingOfferedValueUsdAfter</param>
        /// <param name="offeredAssetCount">offeredAssetCount</param>
        /// <param name="requestedAssetCount">requestedAssetCount</param>
        /// <param name="evaluatedAt">evaluatedAt</param>
        /// <param name="policyEnabled">policyEnabled (default to true)</param>
        [JsonConstructor]
        public V2TradeAuthorizationReceipt(SchemaVersionEnum schemaVersion, long policyRevision, bool allowOutboundGifts, bool requirePartnerAllowlist, bool partnerAllowlisted, int maxOfferedAssets, int maxRequestedAssets, decimal maxOfferedValueUsd, int maxRolling24hTradeCount, decimal maxRolling24hOfferedValueUsd, int rollingTradeCountBefore, decimal rollingOfferedValueUsdBefore, int rollingTradeCountAfter, decimal rollingOfferedValueUsdAfter, int offeredAssetCount, int requestedAssetCount, DateTime evaluatedAt, bool policyEnabled = true)
        {
            SchemaVersion = schemaVersion;
            PolicyRevision = policyRevision;
            AllowOutboundGifts = allowOutboundGifts;
            RequirePartnerAllowlist = requirePartnerAllowlist;
            PartnerAllowlisted = partnerAllowlisted;
            MaxOfferedAssets = maxOfferedAssets;
            MaxRequestedAssets = maxRequestedAssets;
            MaxOfferedValueUsd = maxOfferedValueUsd;
            MaxRolling24hTradeCount = maxRolling24hTradeCount;
            MaxRolling24hOfferedValueUsd = maxRolling24hOfferedValueUsd;
            RollingTradeCountBefore = rollingTradeCountBefore;
            RollingOfferedValueUsdBefore = rollingOfferedValueUsdBefore;
            RollingTradeCountAfter = rollingTradeCountAfter;
            RollingOfferedValueUsdAfter = rollingOfferedValueUsdAfter;
            OfferedAssetCount = offeredAssetCount;
            RequestedAssetCount = requestedAssetCount;
            EvaluatedAt = evaluatedAt;
            PolicyEnabled = policyEnabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines SchemaVersion
        /// </summary>
        public enum SchemaVersionEnum
        {
            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1
        }

        /// <summary>
        /// Returns a <see cref="SchemaVersionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SchemaVersionEnum SchemaVersionEnumFromString(string value)
        {
            if (value.Equals((1).ToString(System.Globalization.CultureInfo.InvariantCulture)))
                return SchemaVersionEnum.NUMBER_1;

            throw new NotImplementedException($"Could not convert value to type SchemaVersionEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SchemaVersionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SchemaVersionEnum? SchemaVersionEnumFromStringOrDefault(string value)
        {
            if (value.Equals((1).ToString(System.Globalization.CultureInfo.InvariantCulture)))
                return SchemaVersionEnum.NUMBER_1;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SchemaVersionEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static int SchemaVersionEnumToJsonValue(SchemaVersionEnum value)
        {
            return (int) value;
        }

        /// <summary>
        /// Gets or Sets SchemaVersion
        /// </summary>
        [JsonPropertyName("schema_version")]
        public SchemaVersionEnum SchemaVersion { get; set; }

        /// <summary>
        /// Gets or Sets PolicyRevision
        /// </summary>
        [JsonPropertyName("policy_revision")]
        public long PolicyRevision { get; set; }

        /// <summary>
        /// Gets or Sets AllowOutboundGifts
        /// </summary>
        [JsonPropertyName("allow_outbound_gifts")]
        public bool AllowOutboundGifts { get; set; }

        /// <summary>
        /// Gets or Sets RequirePartnerAllowlist
        /// </summary>
        [JsonPropertyName("require_partner_allowlist")]
        public bool RequirePartnerAllowlist { get; set; }

        /// <summary>
        /// Whether the exact trade partner was present in the policy allowlist when OpenSkin authorized execution.
        /// </summary>
        /// <value>Whether the exact trade partner was present in the policy allowlist when OpenSkin authorized execution.</value>
        [JsonPropertyName("partner_allowlisted")]
        public bool PartnerAllowlisted { get; set; }

        /// <summary>
        /// Gets or Sets MaxOfferedAssets
        /// </summary>
        [JsonPropertyName("max_offered_assets")]
        public int MaxOfferedAssets { get; set; }

        /// <summary>
        /// Gets or Sets MaxRequestedAssets
        /// </summary>
        [JsonPropertyName("max_requested_assets")]
        public int MaxRequestedAssets { get; set; }

        /// <summary>
        /// Gets or Sets MaxOfferedValueUsd
        /// </summary>
        [JsonPropertyName("max_offered_value_usd")]
        public decimal MaxOfferedValueUsd { get; set; }

        /// <summary>
        /// Gets or Sets MaxRolling24hTradeCount
        /// </summary>
        [JsonPropertyName("max_rolling_24h_trade_count")]
        public int MaxRolling24hTradeCount { get; set; }

        /// <summary>
        /// Gets or Sets MaxRolling24hOfferedValueUsd
        /// </summary>
        [JsonPropertyName("max_rolling_24h_offered_value_usd")]
        public decimal MaxRolling24hOfferedValueUsd { get; set; }

        /// <summary>
        /// Gets or Sets RollingTradeCountBefore
        /// </summary>
        [JsonPropertyName("rolling_trade_count_before")]
        public int RollingTradeCountBefore { get; set; }

        /// <summary>
        /// Gets or Sets RollingOfferedValueUsdBefore
        /// </summary>
        [JsonPropertyName("rolling_offered_value_usd_before")]
        public decimal RollingOfferedValueUsdBefore { get; set; }

        /// <summary>
        /// Gets or Sets RollingTradeCountAfter
        /// </summary>
        [JsonPropertyName("rolling_trade_count_after")]
        public int RollingTradeCountAfter { get; set; }

        /// <summary>
        /// Gets or Sets RollingOfferedValueUsdAfter
        /// </summary>
        [JsonPropertyName("rolling_offered_value_usd_after")]
        public decimal RollingOfferedValueUsdAfter { get; set; }

        /// <summary>
        /// Gets or Sets OfferedAssetCount
        /// </summary>
        [JsonPropertyName("offered_asset_count")]
        public int OfferedAssetCount { get; set; }

        /// <summary>
        /// Gets or Sets RequestedAssetCount
        /// </summary>
        [JsonPropertyName("requested_asset_count")]
        public int RequestedAssetCount { get; set; }

        /// <summary>
        /// Gets or Sets EvaluatedAt
        /// </summary>
        [JsonPropertyName("evaluated_at")]
        public DateTime EvaluatedAt { get; set; }

        /// <summary>
        /// Gets or Sets PolicyEnabled
        /// </summary>
        [JsonPropertyName("policy_enabled")]
        public bool PolicyEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2TradeAuthorizationReceipt {\n");
            sb.Append("  SchemaVersion: ").Append(SchemaVersion).Append("\n");
            sb.Append("  PolicyRevision: ").Append(PolicyRevision).Append("\n");
            sb.Append("  AllowOutboundGifts: ").Append(AllowOutboundGifts).Append("\n");
            sb.Append("  RequirePartnerAllowlist: ").Append(RequirePartnerAllowlist).Append("\n");
            sb.Append("  PartnerAllowlisted: ").Append(PartnerAllowlisted).Append("\n");
            sb.Append("  MaxOfferedAssets: ").Append(MaxOfferedAssets).Append("\n");
            sb.Append("  MaxRequestedAssets: ").Append(MaxRequestedAssets).Append("\n");
            sb.Append("  MaxOfferedValueUsd: ").Append(MaxOfferedValueUsd).Append("\n");
            sb.Append("  MaxRolling24hTradeCount: ").Append(MaxRolling24hTradeCount).Append("\n");
            sb.Append("  MaxRolling24hOfferedValueUsd: ").Append(MaxRolling24hOfferedValueUsd).Append("\n");
            sb.Append("  RollingTradeCountBefore: ").Append(RollingTradeCountBefore).Append("\n");
            sb.Append("  RollingOfferedValueUsdBefore: ").Append(RollingOfferedValueUsdBefore).Append("\n");
            sb.Append("  RollingTradeCountAfter: ").Append(RollingTradeCountAfter).Append("\n");
            sb.Append("  RollingOfferedValueUsdAfter: ").Append(RollingOfferedValueUsdAfter).Append("\n");
            sb.Append("  OfferedAssetCount: ").Append(OfferedAssetCount).Append("\n");
            sb.Append("  RequestedAssetCount: ").Append(RequestedAssetCount).Append("\n");
            sb.Append("  EvaluatedAt: ").Append(EvaluatedAt).Append("\n");
            sb.Append("  PolicyEnabled: ").Append(PolicyEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PolicyRevision (long) minimum
            if (this.PolicyRevision < (long)1)
            {
                yield return new ValidationResult("Invalid value for PolicyRevision, must be a value greater than or equal to 1.", new [] { "PolicyRevision" });
            }

            // MaxOfferedAssets (int) maximum
            if (this.MaxOfferedAssets > (int)255)
            {
                yield return new ValidationResult("Invalid value for MaxOfferedAssets, must be a value less than or equal to 255.", new [] { "MaxOfferedAssets" });
            }

            // MaxOfferedAssets (int) minimum
            if (this.MaxOfferedAssets < (int)1)
            {
                yield return new ValidationResult("Invalid value for MaxOfferedAssets, must be a value greater than or equal to 1.", new [] { "MaxOfferedAssets" });
            }

            // MaxRequestedAssets (int) maximum
            if (this.MaxRequestedAssets > (int)255)
            {
                yield return new ValidationResult("Invalid value for MaxRequestedAssets, must be a value less than or equal to 255.", new [] { "MaxRequestedAssets" });
            }

            // MaxRequestedAssets (int) minimum
            if (this.MaxRequestedAssets < (int)1)
            {
                yield return new ValidationResult("Invalid value for MaxRequestedAssets, must be a value greater than or equal to 1.", new [] { "MaxRequestedAssets" });
            }

            // MaxOfferedValueUsd (decimal) minimum
            if (this.MaxOfferedValueUsd < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for MaxOfferedValueUsd, must be a value greater than or equal to 0.", new [] { "MaxOfferedValueUsd" });
            }

            // MaxRolling24hTradeCount (int) minimum
            if (this.MaxRolling24hTradeCount < (int)1)
            {
                yield return new ValidationResult("Invalid value for MaxRolling24hTradeCount, must be a value greater than or equal to 1.", new [] { "MaxRolling24hTradeCount" });
            }

            // MaxRolling24hOfferedValueUsd (decimal) minimum
            if (this.MaxRolling24hOfferedValueUsd < (decimal)0.01)
            {
                yield return new ValidationResult("Invalid value for MaxRolling24hOfferedValueUsd, must be a value greater than or equal to 0.01.", new [] { "MaxRolling24hOfferedValueUsd" });
            }

            // RollingTradeCountBefore (int) minimum
            if (this.RollingTradeCountBefore < (int)0)
            {
                yield return new ValidationResult("Invalid value for RollingTradeCountBefore, must be a value greater than or equal to 0.", new [] { "RollingTradeCountBefore" });
            }

            // RollingOfferedValueUsdBefore (decimal) minimum
            if (this.RollingOfferedValueUsdBefore < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for RollingOfferedValueUsdBefore, must be a value greater than or equal to 0.", new [] { "RollingOfferedValueUsdBefore" });
            }

            // RollingTradeCountAfter (int) minimum
            if (this.RollingTradeCountAfter < (int)1)
            {
                yield return new ValidationResult("Invalid value for RollingTradeCountAfter, must be a value greater than or equal to 1.", new [] { "RollingTradeCountAfter" });
            }

            // RollingOfferedValueUsdAfter (decimal) minimum
            if (this.RollingOfferedValueUsdAfter < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for RollingOfferedValueUsdAfter, must be a value greater than or equal to 0.", new [] { "RollingOfferedValueUsdAfter" });
            }

            // OfferedAssetCount (int) maximum
            if (this.OfferedAssetCount > (int)255)
            {
                yield return new ValidationResult("Invalid value for OfferedAssetCount, must be a value less than or equal to 255.", new [] { "OfferedAssetCount" });
            }

            // OfferedAssetCount (int) minimum
            if (this.OfferedAssetCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for OfferedAssetCount, must be a value greater than or equal to 0.", new [] { "OfferedAssetCount" });
            }

            // RequestedAssetCount (int) maximum
            if (this.RequestedAssetCount > (int)255)
            {
                yield return new ValidationResult("Invalid value for RequestedAssetCount, must be a value less than or equal to 255.", new [] { "RequestedAssetCount" });
            }

            // RequestedAssetCount (int) minimum
            if (this.RequestedAssetCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RequestedAssetCount, must be a value greater than or equal to 0.", new [] { "RequestedAssetCount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2TradeAuthorizationReceipt" />
    /// </summary>
    public partial class V2TradeAuthorizationReceiptJsonConverter : JsonConverter<V2TradeAuthorizationReceipt>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2TradeAuthorizationReceiptJsonConverter" /> class.
        /// </summary>
        public V2TradeAuthorizationReceiptJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize EvaluatedAt
        /// </summary>
        public string EvaluatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2TradeAuthorizationReceipt" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2TradeAuthorizationReceipt Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2TradeAuthorizationReceipt.SchemaVersionEnum?> schemaVersion = default;
            Option<long?> policyRevision = default;
            Option<bool?> allowOutboundGifts = default;
            Option<bool?> requirePartnerAllowlist = default;
            Option<bool?> partnerAllowlisted = default;
            Option<int?> maxOfferedAssets = default;
            Option<int?> maxRequestedAssets = default;
            Option<decimal?> maxOfferedValueUsd = default;
            Option<int?> maxRolling24hTradeCount = default;
            Option<decimal?> maxRolling24hOfferedValueUsd = default;
            Option<int?> rollingTradeCountBefore = default;
            Option<decimal?> rollingOfferedValueUsdBefore = default;
            Option<int?> rollingTradeCountAfter = default;
            Option<decimal?> rollingOfferedValueUsdAfter = default;
            Option<int?> offeredAssetCount = default;
            Option<int?> requestedAssetCount = default;
            Option<DateTime?> evaluatedAt = default;
            Option<bool?> policyEnabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "schema_version":
                            if (utf8JsonReader.TokenType == JsonTokenType.Null)
                                schemaVersion = new Option<V2TradeAuthorizationReceipt.SchemaVersionEnum?>(null);
                            else
                            {
                                string schemaVersionRawValue = utf8JsonReader.GetInt32().ToString(System.Globalization.CultureInfo.InvariantCulture);
                                V2TradeAuthorizationReceipt.SchemaVersionEnum? schemaVersionValue = V2TradeAuthorizationReceipt.SchemaVersionEnumFromStringOrDefault(schemaVersionRawValue);
                                if (schemaVersionValue == null)
                                    throw new JsonException();
                                schemaVersion = new Option<V2TradeAuthorizationReceipt.SchemaVersionEnum?>(schemaVersionValue);
                            }
                            break;
                        case "policy_revision":
                            policyRevision = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "allow_outbound_gifts":
                            allowOutboundGifts = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "require_partner_allowlist":
                            requirePartnerAllowlist = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "partner_allowlisted":
                            partnerAllowlisted = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "max_offered_assets":
                            maxOfferedAssets = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "max_requested_assets":
                            maxRequestedAssets = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "max_offered_value_usd":
                            maxOfferedValueUsd = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "max_rolling_24h_trade_count":
                            maxRolling24hTradeCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "max_rolling_24h_offered_value_usd":
                            maxRolling24hOfferedValueUsd = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "rolling_trade_count_before":
                            rollingTradeCountBefore = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "rolling_offered_value_usd_before":
                            rollingOfferedValueUsdBefore = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "rolling_trade_count_after":
                            rollingTradeCountAfter = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "rolling_offered_value_usd_after":
                            rollingOfferedValueUsdAfter = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "offered_asset_count":
                            offeredAssetCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "requested_asset_count":
                            requestedAssetCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "evaluated_at":
                            evaluatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "policy_enabled":
                            policyEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!schemaVersion.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(schemaVersion));

            if (!policyRevision.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(policyRevision));

            if (!allowOutboundGifts.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(allowOutboundGifts));

            if (!requirePartnerAllowlist.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(requirePartnerAllowlist));

            if (!partnerAllowlisted.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(partnerAllowlisted));

            if (!maxOfferedAssets.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(maxOfferedAssets));

            if (!maxRequestedAssets.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(maxRequestedAssets));

            if (!maxOfferedValueUsd.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(maxOfferedValueUsd));

            if (!maxRolling24hTradeCount.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(maxRolling24hTradeCount));

            if (!maxRolling24hOfferedValueUsd.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(maxRolling24hOfferedValueUsd));

            if (!rollingTradeCountBefore.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(rollingTradeCountBefore));

            if (!rollingOfferedValueUsdBefore.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(rollingOfferedValueUsdBefore));

            if (!rollingTradeCountAfter.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(rollingTradeCountAfter));

            if (!rollingOfferedValueUsdAfter.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(rollingOfferedValueUsdAfter));

            if (!offeredAssetCount.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(offeredAssetCount));

            if (!requestedAssetCount.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(requestedAssetCount));

            if (!evaluatedAt.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(evaluatedAt));

            if (!policyEnabled.IsSet)
                throw new ArgumentException("Property is required for class V2TradeAuthorizationReceipt.", nameof(policyEnabled));

            if (schemaVersion.IsSet && schemaVersion.Value == null)
                throw new ArgumentNullException(nameof(schemaVersion), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (policyRevision.IsSet && policyRevision.Value == null)
                throw new ArgumentNullException(nameof(policyRevision), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (allowOutboundGifts.IsSet && allowOutboundGifts.Value == null)
                throw new ArgumentNullException(nameof(allowOutboundGifts), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (requirePartnerAllowlist.IsSet && requirePartnerAllowlist.Value == null)
                throw new ArgumentNullException(nameof(requirePartnerAllowlist), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (partnerAllowlisted.IsSet && partnerAllowlisted.Value == null)
                throw new ArgumentNullException(nameof(partnerAllowlisted), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (maxOfferedAssets.IsSet && maxOfferedAssets.Value == null)
                throw new ArgumentNullException(nameof(maxOfferedAssets), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (maxRequestedAssets.IsSet && maxRequestedAssets.Value == null)
                throw new ArgumentNullException(nameof(maxRequestedAssets), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (maxOfferedValueUsd.IsSet && maxOfferedValueUsd.Value == null)
                throw new ArgumentNullException(nameof(maxOfferedValueUsd), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (maxRolling24hTradeCount.IsSet && maxRolling24hTradeCount.Value == null)
                throw new ArgumentNullException(nameof(maxRolling24hTradeCount), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (maxRolling24hOfferedValueUsd.IsSet && maxRolling24hOfferedValueUsd.Value == null)
                throw new ArgumentNullException(nameof(maxRolling24hOfferedValueUsd), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (rollingTradeCountBefore.IsSet && rollingTradeCountBefore.Value == null)
                throw new ArgumentNullException(nameof(rollingTradeCountBefore), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (rollingOfferedValueUsdBefore.IsSet && rollingOfferedValueUsdBefore.Value == null)
                throw new ArgumentNullException(nameof(rollingOfferedValueUsdBefore), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (rollingTradeCountAfter.IsSet && rollingTradeCountAfter.Value == null)
                throw new ArgumentNullException(nameof(rollingTradeCountAfter), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (rollingOfferedValueUsdAfter.IsSet && rollingOfferedValueUsdAfter.Value == null)
                throw new ArgumentNullException(nameof(rollingOfferedValueUsdAfter), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (offeredAssetCount.IsSet && offeredAssetCount.Value == null)
                throw new ArgumentNullException(nameof(offeredAssetCount), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (requestedAssetCount.IsSet && requestedAssetCount.Value == null)
                throw new ArgumentNullException(nameof(requestedAssetCount), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (evaluatedAt.IsSet && evaluatedAt.Value == null)
                throw new ArgumentNullException(nameof(evaluatedAt), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            if (policyEnabled.IsSet && policyEnabled.Value == null)
                throw new ArgumentNullException(nameof(policyEnabled), "Property is not nullable for class V2TradeAuthorizationReceipt.");

            return new V2TradeAuthorizationReceipt(schemaVersion.Value!.Value!, policyRevision.Value!.Value!, allowOutboundGifts.Value!.Value!, requirePartnerAllowlist.Value!.Value!, partnerAllowlisted.Value!.Value!, maxOfferedAssets.Value!.Value!, maxRequestedAssets.Value!.Value!, maxOfferedValueUsd.Value!.Value!, maxRolling24hTradeCount.Value!.Value!, maxRolling24hOfferedValueUsd.Value!.Value!, rollingTradeCountBefore.Value!.Value!, rollingOfferedValueUsdBefore.Value!.Value!, rollingTradeCountAfter.Value!.Value!, rollingOfferedValueUsdAfter.Value!.Value!, offeredAssetCount.Value!.Value!, requestedAssetCount.Value!.Value!, evaluatedAt.Value!.Value!, policyEnabled.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2TradeAuthorizationReceipt" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2TradeAuthorizationReceipt"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2TradeAuthorizationReceipt v2TradeAuthorizationReceipt, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2TradeAuthorizationReceipt, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2TradeAuthorizationReceipt" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2TradeAuthorizationReceipt"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2TradeAuthorizationReceipt v2TradeAuthorizationReceipt, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("schema_version", V2TradeAuthorizationReceipt.SchemaVersionEnumToJsonValue(v2TradeAuthorizationReceipt.SchemaVersion));

            writer.WriteNumber("policy_revision", v2TradeAuthorizationReceipt.PolicyRevision);

            writer.WriteBoolean("allow_outbound_gifts", v2TradeAuthorizationReceipt.AllowOutboundGifts);

            writer.WriteBoolean("require_partner_allowlist", v2TradeAuthorizationReceipt.RequirePartnerAllowlist);

            writer.WriteBoolean("partner_allowlisted", v2TradeAuthorizationReceipt.PartnerAllowlisted);

            writer.WriteNumber("max_offered_assets", v2TradeAuthorizationReceipt.MaxOfferedAssets);

            writer.WriteNumber("max_requested_assets", v2TradeAuthorizationReceipt.MaxRequestedAssets);

            writer.WriteNumber("max_offered_value_usd", v2TradeAuthorizationReceipt.MaxOfferedValueUsd);

            writer.WriteNumber("max_rolling_24h_trade_count", v2TradeAuthorizationReceipt.MaxRolling24hTradeCount);

            writer.WriteNumber("max_rolling_24h_offered_value_usd", v2TradeAuthorizationReceipt.MaxRolling24hOfferedValueUsd);

            writer.WriteNumber("rolling_trade_count_before", v2TradeAuthorizationReceipt.RollingTradeCountBefore);

            writer.WriteNumber("rolling_offered_value_usd_before", v2TradeAuthorizationReceipt.RollingOfferedValueUsdBefore);

            writer.WriteNumber("rolling_trade_count_after", v2TradeAuthorizationReceipt.RollingTradeCountAfter);

            writer.WriteNumber("rolling_offered_value_usd_after", v2TradeAuthorizationReceipt.RollingOfferedValueUsdAfter);

            writer.WriteNumber("offered_asset_count", v2TradeAuthorizationReceipt.OfferedAssetCount);

            writer.WriteNumber("requested_asset_count", v2TradeAuthorizationReceipt.RequestedAssetCount);

            writer.WriteString("evaluated_at", v2TradeAuthorizationReceipt.EvaluatedAt.ToString(EvaluatedAtFormat));

            writer.WriteBoolean("policy_enabled", v2TradeAuthorizationReceipt.PolicyEnabled);
        }
    }
}
