// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2TradeIntentExecution
    /// </summary>
    public partial class V2TradeIntentExecution : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2TradeIntentExecution" /> class.
        /// </summary>
        /// <param name="intent">intent</param>
        /// <param name="trade">trade</param>
        /// <param name="command">command</param>
        [JsonConstructor]
        public V2TradeIntentExecution(V2TradeIntent intent, V2TradeOperation trade, V2CommandReceipt command)
        {
            Intent = intent;
            Trade = trade;
            Command = command;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Intent
        /// </summary>
        [JsonPropertyName("intent")]
        public V2TradeIntent Intent { get; set; }

        /// <summary>
        /// Gets or Sets Trade
        /// </summary>
        [JsonPropertyName("trade")]
        public V2TradeOperation Trade { get; set; }

        /// <summary>
        /// Gets or Sets Command
        /// </summary>
        [JsonPropertyName("command")]
        public V2CommandReceipt Command { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2TradeIntentExecution {\n");
            sb.Append("  Intent: ").Append(Intent).Append("\n");
            sb.Append("  Trade: ").Append(Trade).Append("\n");
            sb.Append("  Command: ").Append(Command).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2TradeIntentExecution" />
    /// </summary>
    public partial class V2TradeIntentExecutionJsonConverter : JsonConverter<V2TradeIntentExecution>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2TradeIntentExecutionJsonConverter" /> class.
        /// </summary>
        public V2TradeIntentExecutionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2TradeIntentExecution" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2TradeIntentExecution Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2TradeIntent?> intent = default;
            Option<V2TradeOperation?> trade = default;
            Option<V2CommandReceipt?> command = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "intent":
                            intent = new Option<V2TradeIntent?>(JsonSerializer.Deserialize<V2TradeIntent>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "trade":
                            trade = new Option<V2TradeOperation?>(JsonSerializer.Deserialize<V2TradeOperation>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "command":
                            command = new Option<V2CommandReceipt?>(JsonSerializer.Deserialize<V2CommandReceipt>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!intent.IsSet)
                throw new ArgumentException("Property is required for class V2TradeIntentExecution.", nameof(intent));

            if (!trade.IsSet)
                throw new ArgumentException("Property is required for class V2TradeIntentExecution.", nameof(trade));

            if (!command.IsSet)
                throw new ArgumentException("Property is required for class V2TradeIntentExecution.", nameof(command));

            if (intent.IsSet && intent.Value == null)
                throw new ArgumentNullException(nameof(intent), "Property is not nullable for class V2TradeIntentExecution.");

            if (trade.IsSet && trade.Value == null)
                throw new ArgumentNullException(nameof(trade), "Property is not nullable for class V2TradeIntentExecution.");

            if (command.IsSet && command.Value == null)
                throw new ArgumentNullException(nameof(command), "Property is not nullable for class V2TradeIntentExecution.");

            return new V2TradeIntentExecution(intent.Value!, trade.Value!, command.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2TradeIntentExecution" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2TradeIntentExecution"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2TradeIntentExecution v2TradeIntentExecution, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2TradeIntentExecution, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2TradeIntentExecution" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2TradeIntentExecution"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2TradeIntentExecution v2TradeIntentExecution, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2TradeIntentExecution.Intent == null)
                throw new ArgumentNullException(nameof(v2TradeIntentExecution.Intent), "Property is required for class V2TradeIntentExecution.");

            if (v2TradeIntentExecution.Trade == null)
                throw new ArgumentNullException(nameof(v2TradeIntentExecution.Trade), "Property is required for class V2TradeIntentExecution.");

            if (v2TradeIntentExecution.Command == null)
                throw new ArgumentNullException(nameof(v2TradeIntentExecution.Command), "Property is required for class V2TradeIntentExecution.");

            writer.WritePropertyName("intent");
            JsonSerializer.Serialize(writer, v2TradeIntentExecution.Intent, jsonSerializerOptions);
            writer.WritePropertyName("trade");
            JsonSerializer.Serialize(writer, v2TradeIntentExecution.Trade, jsonSerializerOptions);
            writer.WritePropertyName("command");
            JsonSerializer.Serialize(writer, v2TradeIntentExecution.Command, jsonSerializerOptions);
        }
    }
}
