// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2UsageOperation
    /// </summary>
    public partial class V2UsageOperation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2UsageOperation" /> class.
        /// </summary>
        /// <param name="operation">operation</param>
        /// <param name="requests">requests</param>
        /// <param name="units">units</param>
        /// <param name="errors">errors</param>
        [JsonConstructor]
        public V2UsageOperation(string operation, long requests, long units, long errors)
        {
            Operation = operation;
            Requests = requests;
            Units = units;
            Errors = errors;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Operation
        /// </summary>
        [JsonPropertyName("operation")]
        public string Operation { get; set; }

        /// <summary>
        /// Gets or Sets Requests
        /// </summary>
        [JsonPropertyName("requests")]
        public long Requests { get; set; }

        /// <summary>
        /// Gets or Sets Units
        /// </summary>
        [JsonPropertyName("units")]
        public long Units { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [JsonPropertyName("errors")]
        public long Errors { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2UsageOperation {\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  Requests: ").Append(Requests).Append("\n");
            sb.Append("  Units: ").Append(Units).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Operation != null) {
                // Operation (string) pattern
                Regex regexOperation = new Regex(@"^[a-z0-9_.]{1,96}$", RegexOptions.CultureInvariant);

                if (!regexOperation.Match(this.Operation).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Operation, must match a pattern of " + regexOperation, new [] { "Operation" });
                }
            }

            // Requests (long) minimum
            if (this.Requests < (long)0)
            {
                yield return new ValidationResult("Invalid value for Requests, must be a value greater than or equal to 0.", new [] { "Requests" });
            }

            // Units (long) minimum
            if (this.Units < (long)0)
            {
                yield return new ValidationResult("Invalid value for Units, must be a value greater than or equal to 0.", new [] { "Units" });
            }

            // Errors (long) minimum
            if (this.Errors < (long)0)
            {
                yield return new ValidationResult("Invalid value for Errors, must be a value greater than or equal to 0.", new [] { "Errors" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2UsageOperation" />
    /// </summary>
    public partial class V2UsageOperationJsonConverter : JsonConverter<V2UsageOperation>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2UsageOperationJsonConverter" /> class.
        /// </summary>
        public V2UsageOperationJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2UsageOperation" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2UsageOperation Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> operation = default;
            Option<long?> requests = default;
            Option<long?> units = default;
            Option<long?> errors = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "operation":
                            operation = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "requests":
                            requests = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "units":
                            units = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "errors":
                            errors = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!operation.IsSet)
                throw new ArgumentException("Property is required for class V2UsageOperation.", nameof(operation));

            if (!requests.IsSet)
                throw new ArgumentException("Property is required for class V2UsageOperation.", nameof(requests));

            if (!units.IsSet)
                throw new ArgumentException("Property is required for class V2UsageOperation.", nameof(units));

            if (!errors.IsSet)
                throw new ArgumentException("Property is required for class V2UsageOperation.", nameof(errors));

            if (operation.IsSet && operation.Value == null)
                throw new ArgumentNullException(nameof(operation), "Property is not nullable for class V2UsageOperation.");

            if (requests.IsSet && requests.Value == null)
                throw new ArgumentNullException(nameof(requests), "Property is not nullable for class V2UsageOperation.");

            if (units.IsSet && units.Value == null)
                throw new ArgumentNullException(nameof(units), "Property is not nullable for class V2UsageOperation.");

            if (errors.IsSet && errors.Value == null)
                throw new ArgumentNullException(nameof(errors), "Property is not nullable for class V2UsageOperation.");

            return new V2UsageOperation(operation.Value!, requests.Value!.Value!, units.Value!.Value!, errors.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V2UsageOperation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2UsageOperation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2UsageOperation v2UsageOperation, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2UsageOperation, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2UsageOperation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2UsageOperation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2UsageOperation v2UsageOperation, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2UsageOperation.Operation == null)
                throw new ArgumentNullException(nameof(v2UsageOperation.Operation), "Property is required for class V2UsageOperation.");

            writer.WriteString("operation", v2UsageOperation.Operation);

            writer.WriteNumber("requests", v2UsageOperation.Requests);

            writer.WriteNumber("units", v2UsageOperation.Units);

            writer.WriteNumber("errors", v2UsageOperation.Errors);
        }
    }
}
