// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2WebhookDelivery
    /// </summary>
    public partial class V2WebhookDelivery : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2WebhookDelivery" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="endpointId">endpointId</param>
        /// <param name="eventId">eventId</param>
        /// <param name="eventType">eventType</param>
        /// <param name="state">state</param>
        /// <param name="attemptCount">attemptCount</param>
        /// <param name="nextAttemptAt">nextAttemptAt</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="deliveredAt">deliveredAt</param>
        /// <param name="lastErrorCode">lastErrorCode</param>
        /// <param name="replayOfDeliveryId">The terminal failed delivery that the customer explicitly retried. Omitted for original fanout.</param>
        [JsonConstructor]
        public V2WebhookDelivery(Guid id, Guid endpointId, Guid eventId, string eventType, StateEnum state, int attemptCount, DateTime nextAttemptAt, DateTime createdAt, DateTime updatedAt, Option<DateTime?> deliveredAt = default, Option<string?> lastErrorCode = default, Option<Guid?> replayOfDeliveryId = default)
        {
            Id = id;
            EndpointId = endpointId;
            EventId = eventId;
            EventType = eventType;
            State = state;
            AttemptCount = attemptCount;
            NextAttemptAt = nextAttemptAt;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            DeliveredAtOption = deliveredAt;
            LastErrorCodeOption = lastErrorCode;
            ReplayOfDeliveryIdOption = replayOfDeliveryId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines State
        /// </summary>
        public enum StateEnum
        {
            /// <summary>
            /// Enum Queued for value: queued
            /// </summary>
            Queued = 1,

            /// <summary>
            /// Enum Delivering for value: delivering
            /// </summary>
            Delivering = 2,

            /// <summary>
            /// Enum Retry for value: retry
            /// </summary>
            Retry = 3,

            /// <summary>
            /// Enum Succeeded for value: succeeded
            /// </summary>
            Succeeded = 4,

            /// <summary>
            /// Enum Dead for value: dead
            /// </summary>
            Dead = 5
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StateEnum StateEnumFromString(string value)
        {
            if (value.Equals("queued"))
                return StateEnum.Queued;

            if (value.Equals("delivering"))
                return StateEnum.Delivering;

            if (value.Equals("retry"))
                return StateEnum.Retry;

            if (value.Equals("succeeded"))
                return StateEnum.Succeeded;

            if (value.Equals("dead"))
                return StateEnum.Dead;

            throw new NotImplementedException($"Could not convert value to type StateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StateEnum? StateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("queued"))
                return StateEnum.Queued;

            if (value.Equals("delivering"))
                return StateEnum.Delivering;

            if (value.Equals("retry"))
                return StateEnum.Retry;

            if (value.Equals("succeeded"))
                return StateEnum.Succeeded;

            if (value.Equals("dead"))
                return StateEnum.Dead;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StateEnumToJsonValue(StateEnum value)
        {
            if (value == StateEnum.Queued)
                return "queued";

            if (value == StateEnum.Delivering)
                return "delivering";

            if (value == StateEnum.Retry)
                return "retry";

            if (value == StateEnum.Succeeded)
                return "succeeded";

            if (value == StateEnum.Dead)
                return "dead";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public StateEnum State { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets EndpointId
        /// </summary>
        [JsonPropertyName("endpoint_id")]
        public Guid EndpointId { get; set; }

        /// <summary>
        /// Gets or Sets EventId
        /// </summary>
        [JsonPropertyName("event_id")]
        public Guid EventId { get; set; }

        /// <summary>
        /// Gets or Sets EventType
        /// </summary>
        [JsonPropertyName("event_type")]
        public string EventType { get; set; }

        /// <summary>
        /// Gets or Sets AttemptCount
        /// </summary>
        [JsonPropertyName("attempt_count")]
        public int AttemptCount { get; set; }

        /// <summary>
        /// Gets or Sets NextAttemptAt
        /// </summary>
        [JsonPropertyName("next_attempt_at")]
        public DateTime NextAttemptAt { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of DeliveredAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DeliveredAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeliveredAt
        /// </summary>
        [JsonPropertyName("delivered_at")]
        public DateTime? DeliveredAt { get { return this.DeliveredAtOption.Value; } set { this.DeliveredAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastErrorCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastErrorCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastErrorCode
        /// </summary>
        [JsonPropertyName("last_error_code")]
        public string? LastErrorCode { get { return this.LastErrorCodeOption.Value; } set { this.LastErrorCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReplayOfDeliveryId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ReplayOfDeliveryIdOption { get; private set; }

        /// <summary>
        /// The terminal failed delivery that the customer explicitly retried. Omitted for original fanout.
        /// </summary>
        /// <value>The terminal failed delivery that the customer explicitly retried. Omitted for original fanout.</value>
        [JsonPropertyName("replay_of_delivery_id")]
        public Guid? ReplayOfDeliveryId { get { return this.ReplayOfDeliveryIdOption.Value; } set { this.ReplayOfDeliveryIdOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2WebhookDelivery {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  EndpointId: ").Append(EndpointId).Append("\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  AttemptCount: ").Append(AttemptCount).Append("\n");
            sb.Append("  NextAttemptAt: ").Append(NextAttemptAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  DeliveredAt: ").Append(DeliveredAt).Append("\n");
            sb.Append("  LastErrorCode: ").Append(LastErrorCode).Append("\n");
            sb.Append("  ReplayOfDeliveryId: ").Append(ReplayOfDeliveryId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AttemptCount (int) maximum
            if (this.AttemptCount > (int)8)
            {
                yield return new ValidationResult("Invalid value for AttemptCount, must be a value less than or equal to 8.", new [] { "AttemptCount" });
            }

            // AttemptCount (int) minimum
            if (this.AttemptCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for AttemptCount, must be a value greater than or equal to 0.", new [] { "AttemptCount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2WebhookDelivery" />
    /// </summary>
    public partial class V2WebhookDeliveryJsonConverter : JsonConverter<V2WebhookDelivery>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2WebhookDeliveryJsonConverter" /> class.
        /// </summary>
        public V2WebhookDeliveryJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize NextAttemptAt
        /// </summary>
        public string NextAttemptAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DeliveredAt
        /// </summary>
        public string DeliveredAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V2WebhookDelivery" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2WebhookDelivery Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> endpointId = default;
            Option<Guid?> eventId = default;
            Option<string?> eventType = default;
            Option<V2WebhookDelivery.StateEnum?> state = default;
            Option<int?> attemptCount = default;
            Option<DateTime?> nextAttemptAt = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<DateTime?> deliveredAt = default;
            Option<string?> lastErrorCode = default;
            Option<Guid?> replayOfDeliveryId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "endpoint_id":
                            endpointId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "event_id":
                            eventId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "event_type":
                            eventType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                            {
                                V2WebhookDelivery.StateEnum? stateValue = V2WebhookDelivery.StateEnumFromStringOrDefault(stateRawValue);
                                if (stateValue == null)
                                    throw new JsonException();
                                state = new Option<V2WebhookDelivery.StateEnum?>(stateValue);
                            }
                            break;
                        case "attempt_count":
                            attemptCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "next_attempt_at":
                            nextAttemptAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "delivered_at":
                            deliveredAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "last_error_code":
                            lastErrorCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "replay_of_delivery_id":
                            replayOfDeliveryId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(id));

            if (!endpointId.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(endpointId));

            if (!eventId.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(eventId));

            if (!eventType.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(eventType));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(state));

            if (!attemptCount.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(attemptCount));

            if (!nextAttemptAt.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(nextAttemptAt));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookDelivery.", nameof(updatedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class V2WebhookDelivery.");

            if (endpointId.IsSet && endpointId.Value == null)
                throw new ArgumentNullException(nameof(endpointId), "Property is not nullable for class V2WebhookDelivery.");

            if (eventId.IsSet && eventId.Value == null)
                throw new ArgumentNullException(nameof(eventId), "Property is not nullable for class V2WebhookDelivery.");

            if (eventType.IsSet && eventType.Value == null)
                throw new ArgumentNullException(nameof(eventType), "Property is not nullable for class V2WebhookDelivery.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class V2WebhookDelivery.");

            if (attemptCount.IsSet && attemptCount.Value == null)
                throw new ArgumentNullException(nameof(attemptCount), "Property is not nullable for class V2WebhookDelivery.");

            if (nextAttemptAt.IsSet && nextAttemptAt.Value == null)
                throw new ArgumentNullException(nameof(nextAttemptAt), "Property is not nullable for class V2WebhookDelivery.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class V2WebhookDelivery.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class V2WebhookDelivery.");

            if (deliveredAt.IsSet && deliveredAt.Value == null)
                throw new ArgumentNullException(nameof(deliveredAt), "Property is not nullable for class V2WebhookDelivery.");

            if (lastErrorCode.IsSet && lastErrorCode.Value == null)
                throw new ArgumentNullException(nameof(lastErrorCode), "Property is not nullable for class V2WebhookDelivery.");

            if (replayOfDeliveryId.IsSet && replayOfDeliveryId.Value == null)
                throw new ArgumentNullException(nameof(replayOfDeliveryId), "Property is not nullable for class V2WebhookDelivery.");

            return new V2WebhookDelivery(id.Value!.Value!, endpointId.Value!.Value!, eventId.Value!.Value!, eventType.Value!, state.Value!.Value!, attemptCount.Value!.Value!, nextAttemptAt.Value!.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, deliveredAt, lastErrorCode, replayOfDeliveryId);
        }

        /// <summary>
        /// Serializes a <see cref="V2WebhookDelivery" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2WebhookDelivery"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2WebhookDelivery v2WebhookDelivery, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2WebhookDelivery, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2WebhookDelivery" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2WebhookDelivery"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2WebhookDelivery v2WebhookDelivery, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2WebhookDelivery.EventType == null)
                throw new ArgumentNullException(nameof(v2WebhookDelivery.EventType), "Property is required for class V2WebhookDelivery.");

            if (v2WebhookDelivery.LastErrorCodeOption.IsSet && v2WebhookDelivery.LastErrorCode == null)
                throw new ArgumentNullException(nameof(v2WebhookDelivery.LastErrorCode), "Property is required for class V2WebhookDelivery.");

            writer.WriteString("id", v2WebhookDelivery.Id);

            writer.WriteString("endpoint_id", v2WebhookDelivery.EndpointId);

            writer.WriteString("event_id", v2WebhookDelivery.EventId);

            writer.WriteString("event_type", v2WebhookDelivery.EventType);

            var stateRawValue = V2WebhookDelivery.StateEnumToJsonValue(v2WebhookDelivery.State);
            writer.WriteString("state", stateRawValue);
            writer.WriteNumber("attempt_count", v2WebhookDelivery.AttemptCount);

            writer.WriteString("next_attempt_at", v2WebhookDelivery.NextAttemptAt.ToString(NextAttemptAtFormat));

            writer.WriteString("created_at", v2WebhookDelivery.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updated_at", v2WebhookDelivery.UpdatedAt.ToString(UpdatedAtFormat));

            if (v2WebhookDelivery.DeliveredAtOption.IsSet)
                writer.WriteString("delivered_at", v2WebhookDelivery.DeliveredAtOption.Value!.Value.ToString(DeliveredAtFormat));

            if (v2WebhookDelivery.LastErrorCodeOption.IsSet)
                writer.WriteString("last_error_code", v2WebhookDelivery.LastErrorCode);

            if (v2WebhookDelivery.ReplayOfDeliveryIdOption.IsSet)
                writer.WriteString("replay_of_delivery_id", v2WebhookDelivery.ReplayOfDeliveryIdOption.Value!.Value);
        }
    }
}
