// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2WebhookSecretReceipt
    /// </summary>
    public partial class V2WebhookSecretReceipt : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2WebhookSecretReceipt" /> class.
        /// </summary>
        /// <param name="endpoint">endpoint</param>
        /// <param name="secretVersion">secretVersion</param>
        /// <param name="created">created</param>
        /// <param name="signingSecret">Returned once for a newly created secret; omitted on idempotent replay</param>
        [JsonConstructor]
        public V2WebhookSecretReceipt(V2WebhookEndpoint endpoint, int secretVersion, bool created, Option<string?> signingSecret = default)
        {
            Endpoint = endpoint;
            SecretVersion = secretVersion;
            Created = created;
            SigningSecretOption = signingSecret;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Endpoint
        /// </summary>
        [JsonPropertyName("endpoint")]
        public V2WebhookEndpoint Endpoint { get; set; }

        /// <summary>
        /// Gets or Sets SecretVersion
        /// </summary>
        [JsonPropertyName("secret_version")]
        public int SecretVersion { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public bool Created { get; set; }

        /// <summary>
        /// Used to track the state of SigningSecret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SigningSecretOption { get; private set; }

        /// <summary>
        /// Returned once for a newly created secret; omitted on idempotent replay
        /// </summary>
        /// <value>Returned once for a newly created secret; omitted on idempotent replay</value>
        [JsonPropertyName("signing_secret")]
        public string? SigningSecret { get { return this.SigningSecretOption.Value; } set { this.SigningSecretOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2WebhookSecretReceipt {\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("  SecretVersion: ").Append(SecretVersion).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  SigningSecret: ").Append(SigningSecret).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SecretVersion (int) minimum
            if (this.SecretVersion < (int)1)
            {
                yield return new ValidationResult("Invalid value for SecretVersion, must be a value greater than or equal to 1.", new [] { "SecretVersion" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2WebhookSecretReceipt" />
    /// </summary>
    public partial class V2WebhookSecretReceiptJsonConverter : JsonConverter<V2WebhookSecretReceipt>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2WebhookSecretReceiptJsonConverter" /> class.
        /// </summary>
        public V2WebhookSecretReceiptJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2WebhookSecretReceipt" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2WebhookSecretReceipt Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<V2WebhookEndpoint?> endpoint = default;
            Option<int?> secretVersion = default;
            Option<bool?> created = default;
            Option<string?> signingSecret = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "endpoint":
                            endpoint = new Option<V2WebhookEndpoint?>(JsonSerializer.Deserialize<V2WebhookEndpoint>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "secret_version":
                            secretVersion = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "created":
                            created = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "signing_secret":
                            signingSecret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!endpoint.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookSecretReceipt.", nameof(endpoint));

            if (!secretVersion.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookSecretReceipt.", nameof(secretVersion));

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookSecretReceipt.", nameof(created));

            if (endpoint.IsSet && endpoint.Value == null)
                throw new ArgumentNullException(nameof(endpoint), "Property is not nullable for class V2WebhookSecretReceipt.");

            if (secretVersion.IsSet && secretVersion.Value == null)
                throw new ArgumentNullException(nameof(secretVersion), "Property is not nullable for class V2WebhookSecretReceipt.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class V2WebhookSecretReceipt.");

            if (signingSecret.IsSet && signingSecret.Value == null)
                throw new ArgumentNullException(nameof(signingSecret), "Property is not nullable for class V2WebhookSecretReceipt.");

            return new V2WebhookSecretReceipt(endpoint.Value!, secretVersion.Value!.Value!, created.Value!.Value!, signingSecret);
        }

        /// <summary>
        /// Serializes a <see cref="V2WebhookSecretReceipt" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2WebhookSecretReceipt"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2WebhookSecretReceipt v2WebhookSecretReceipt, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2WebhookSecretReceipt, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2WebhookSecretReceipt" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2WebhookSecretReceipt"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2WebhookSecretReceipt v2WebhookSecretReceipt, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2WebhookSecretReceipt.Endpoint == null)
                throw new ArgumentNullException(nameof(v2WebhookSecretReceipt.Endpoint), "Property is required for class V2WebhookSecretReceipt.");

            if (v2WebhookSecretReceipt.SigningSecretOption.IsSet && v2WebhookSecretReceipt.SigningSecret == null)
                throw new ArgumentNullException(nameof(v2WebhookSecretReceipt.SigningSecret), "Property is required for class V2WebhookSecretReceipt.");

            writer.WritePropertyName("endpoint");
            JsonSerializer.Serialize(writer, v2WebhookSecretReceipt.Endpoint, jsonSerializerOptions);
            writer.WriteNumber("secret_version", v2WebhookSecretReceipt.SecretVersion);

            writer.WriteBoolean("created", v2WebhookSecretReceipt.Created);

            if (v2WebhookSecretReceipt.SigningSecretOption.IsSet)
                writer.WriteString("signing_secret", v2WebhookSecretReceipt.SigningSecret);
        }
    }
}
