// <auto-generated>
/*
 * OpenSkin Platform API
 *
 * Catalog, pricing, inventory, inspect, media, Steam profile, trading, and webhook APIs for CS2 applications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@openskin.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenSkin.Client.Client;

namespace OpenSkin.Client.Model
{
    /// <summary>
    /// V2WebhookEndpointRequest
    /// </summary>
    public partial class V2WebhookEndpointRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2WebhookEndpointRequest" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="eventTypes">eventTypes</param>
        /// <param name="description">description</param>
        [JsonConstructor]
        public V2WebhookEndpointRequest(string url, List<string> eventTypes, Option<string?> description = default)
        {
            Url = url;
            EventTypes = eventTypes;
            DescriptionOption = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets EventTypes
        /// </summary>
        [JsonPropertyName("event_types")]
        public List<string> EventTypes { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2WebhookEndpointRequest {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  EventTypes: ").Append(EventTypes).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Url (string) maxLength
            if (this.Url != null && this.Url.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for Url, length must be less than 2048.", new [] { "Url" });
            }

            if (this.Url != null) {
                // Url (string) pattern
                Regex regexUrl = new Regex(@"^https://", RegexOptions.CultureInvariant);

                if (!regexUrl.Match(this.Url).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Url, must match a pattern of " + regexUrl, new [] { "Url" });
                }
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 200.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V2WebhookEndpointRequest" />
    /// </summary>
    public partial class V2WebhookEndpointRequestJsonConverter : JsonConverter<V2WebhookEndpointRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="V2WebhookEndpointRequestJsonConverter" /> class.
        /// </summary>
        public V2WebhookEndpointRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="V2WebhookEndpointRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V2WebhookEndpointRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<List<string>?> eventTypes = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "event_types":
                            eventTypes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookEndpointRequest.", nameof(url));

            if (!eventTypes.IsSet)
                throw new ArgumentException("Property is required for class V2WebhookEndpointRequest.", nameof(eventTypes));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class V2WebhookEndpointRequest.");

            if (eventTypes.IsSet && eventTypes.Value == null)
                throw new ArgumentNullException(nameof(eventTypes), "Property is not nullable for class V2WebhookEndpointRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class V2WebhookEndpointRequest.");

            return new V2WebhookEndpointRequest(url.Value!, eventTypes.Value!, description);
        }

        /// <summary>
        /// Serializes a <see cref="V2WebhookEndpointRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2WebhookEndpointRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V2WebhookEndpointRequest v2WebhookEndpointRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v2WebhookEndpointRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V2WebhookEndpointRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v2WebhookEndpointRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V2WebhookEndpointRequest v2WebhookEndpointRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v2WebhookEndpointRequest.Url == null)
                throw new ArgumentNullException(nameof(v2WebhookEndpointRequest.Url), "Property is required for class V2WebhookEndpointRequest.");

            if (v2WebhookEndpointRequest.EventTypes == null)
                throw new ArgumentNullException(nameof(v2WebhookEndpointRequest.EventTypes), "Property is required for class V2WebhookEndpointRequest.");

            if (v2WebhookEndpointRequest.DescriptionOption.IsSet && v2WebhookEndpointRequest.Description == null)
                throw new ArgumentNullException(nameof(v2WebhookEndpointRequest.Description), "Property is required for class V2WebhookEndpointRequest.");

            writer.WriteString("url", v2WebhookEndpointRequest.Url);

            writer.WritePropertyName("event_types");
            JsonSerializer.Serialize(writer, v2WebhookEndpointRequest.EventTypes, jsonSerializerOptions);
            if (v2WebhookEndpointRequest.DescriptionOption.IsSet)
                writer.WriteString("description", v2WebhookEndpointRequest.Description);
        }
    }
}
