name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  nuget:
    runs-on: ubuntu-latest
    environment: nuget
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet pack src/OpenSkin.Client/OpenSkin.Client.csproj --configuration Release --output artifacts
      - run: dotnet nuget push 'artifacts/*.nupkg' --api-key '${{ secrets.NUGET_API_KEY }}' --source https://api.nuget.org/v3/index.json --skip-duplicate
